export interface GroceryCatalogItem {
  id: string;
  className: string;
  nameFr: string;
  nameEn: string;
  category: string;
  categoryFr: string;
  location: 'Fridge' | 'Pantry' | 'Freezer';
  shelfLife: number;
  pluCode?: string;
  calories: number;
  originFr: string;
  originEn: string;
  brand: string;
  packagingFormatFr: string;
  packagingFormatEn: string;
  dietaryBadges: string[];
  storageTipFr: string;
  storageTipEn: string;
  freezerTipFr: string;
  freezerTipEn: string;
  nutritionSummary: string;
}

export const GROCERY_CLASSES_81: string[] = [
  'Golden-Delicious',
  'Granny-Smith',
  'Pink-Lady',
  'Red-Delicious',
  'Royal-Gala',
  'Avocado',
  'Banana',
  'Kiwi',
  'Lemon',
  'Lime',
  'Mango',
  'Cantaloupe',
  'Galia-Melon',
  'Honeydew-Melon',
  'Watermelon',
  'Nectarine',
  'Orange',
  'Papaya',
  'Passion-Fruit',
  'Peach',
  'Anjou',
  'Conference',
  'Kaiser',
  'Pineapple',
  'Plum',
  'Pomegranate',
  'Red-Grapefruit',
  'Satsumas',
  'Bravo-Apple-Juice',
  'Bravo-Orange-Juice',
  'God-Morgon-Apple-Juice',
  'God-Morgon-Orange-Juice',
  'God-Morgon-Orange-Red-Grapefruit-Juice',
  'God-Morgon-Red-Grapefruit-Juice',
  'Tropicana-Apple-Juice',
  'Tropicana-Golden-Grapefruit',
  'Tropicana-Juice-Smooth',
  'Tropicana-Mandarin-Morning',
  'Arla-Ecological-Medium-Fat-Milk',
  'Arla-Lactose-Medium-Fat-Milk',
  'Arla-Medium-Fat-Milk',
  'Arla-Standard-Milk',
  'Garant-Ecological-Medium-Fat-Milk',
  'Garant-Ecological-Standard-Milk',
  'Oatly-Natural-Oatghurt',
  'Oatly-Oat-Milk',
  'Arla-Ecological-Sour-Cream',
  'Arla-Sour-Cream',
  'Arla-Sour-Milk',
  'Alpro-Blueberry-Soyghurt',
  'Alpro-Vanilla-Soyghurt',
  'Alpro-Fresh-Soy-Milk',
  'Alpro-Shelf-Soy-Milk',
  'Arla-Mild-Vanilla-Yoghurt',
  'Arla-Natural-Mild-Low-Fat-Yoghurt',
  'Arla-Natural-Yoghurt',
  'Valio-Vanilla-Yoghurt',
  'Yoggi-Strawberry-Yoghurt',
  'Yoggi-Vanilla-Yoghurt',
  'Asparagus',
  'Aubergine',
  'Cabbage',
  'Carrots',
  'Cucumber',
  'Garlic',
  'Ginger',
  'Leek',
  'Brown-Cap-Mushroom',
  'Yellow-Onion',
  'Green-Bell-Pepper',
  'Orange-Bell-Pepper',
  'Red-Bell-Pepper',
  'Yellow-Bell-Pepper',
  'Floury-Potato',
  'Solid-Potato',
  'Sweet-Potato',
  'Red-Beet',
  'Beef-Tomato',
  'Regular-Tomato',
  'Vine-Tomato',
  'Zucchini',
];

export const GROCERY_CATALOG: Record<string, GroceryCatalogItem> = {
  'golden-delicious': {
    id: 'golden-delicious',
    className: 'Golden-Delicious',
    nameFr: 'Pomme Golden Delicious fraîche',
    nameEn: 'Fresh Golden Delicious Apple',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 28,
    pluCode: '4021',
    calories: 52,
    originFr: 'Pommes du Québec / Canada No. 1 (PLU #4021)',
    originEn: 'Canada No. 1 Fresh Apple (PLU #4021)',
    brand: 'Vergers du Québec',
    packagingFormatFr: 'Fruit frais en vrac',
    packagingFormatEn: 'Fresh loose produce',
    dietaryBadges: ['Produits frais', 'Code PLU #4021', 'Aliments du Québec'],
    storageTipFr: 'Conserver au tiroir à fruits du réfrigérateur pour préserver sa douceur croquante.',
    storageTipEn: 'Store in the crisper drawer of your refrigerator to maintain crisp sweetness.',
    freezerTipFr: 'Évider, trancher et arroser d’un trait de citron avant de congeler.',
    freezerTipEn: 'Core, slice and toss with a touch of lemon juice before freezing.',
    nutritionSummary: '52 kcal • 100% frais • Riche en fibres',
  },
  'granny-smith': {
    id: 'granny-smith',
    className: 'Granny-Smith',
    nameFr: 'Pomme Granny Smith verte acidulée',
    nameEn: 'Fresh Tart Granny Smith Apple',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 30,
    pluCode: '4017',
    calories: 50,
    originFr: 'Canada No. 1 • Pastille PLU #4017',
    originEn: 'Canada No. 1 • PLU Sticker #4017',
    brand: 'Sélection Vergers',
    packagingFormatFr: 'Fruit frais en vrac',
    packagingFormatEn: 'Fresh loose produce',
    dietaryBadges: ['Produits frais', 'Code PLU #4017'],
    storageTipFr: 'Excellente tenue au réfrigérateur jusqu’à un mois. Idéale en tarte ou salade.',
    storageTipEn: 'Keeps firm in the fridge crisper up to 4 weeks. Ideal for baking or salads.',
    freezerTipFr: 'Peler, couper en quartiers pour tartes aux pommes maison.',
    freezerTipEn: 'Peel, core and freeze in wedges for homemade apple crisps.',
    nutritionSummary: '50 kcal • Riche en vitamine C & antioxydants',
  },
  'pink-lady': {
    id: 'pink-lady',
    className: 'Pink-Lady',
    nameFr: 'Pomme Pink Lady (Cripps Pink)',
    nameEn: 'Pink Lady (Cripps Pink) Apple',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 25,
    pluCode: '4128',
    calories: 54,
    originFr: 'Qualité supérieure • PLU #4128',
    originEn: 'Premium Grade • PLU #4128',
    brand: 'Sélection Pommes',
    packagingFormatFr: 'Fruit frais en vrac',
    packagingFormatEn: 'Fresh loose produce',
    dietaryBadges: ['Produits frais', 'Code PLU #4128'],
    storageTipFr: 'Conserver au frais. Équilibre parfait entre douceur et acidité.',
    storageTipEn: 'Keep refrigerated. Perfect sweet-tart crunch.',
    freezerTipFr: 'Congeler en tranches fines pour compote ou smoothies.',
    freezerTipEn: 'Freeze in slices for compotes or smoothies.',
    nutritionSummary: '54 kcal • Croquante & juteuse',
  },
  'red-delicious': {
    id: 'red-delicious',
    className: 'Red-Delicious',
    nameFr: 'Pomme Red Delicious rouge vif',
    nameEn: 'Red Delicious Apple',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 21,
    pluCode: '4016',
    calories: 52,
    originFr: 'Canada No. 1 • PLU #4016',
    originEn: 'Canada No. 1 • PLU #4016',
    brand: 'Vergers Locaux',
    packagingFormatFr: 'Fruit frais en vrac',
    packagingFormatEn: 'Fresh loose produce',
    dietaryBadges: ['Produits frais', 'Code PLU #4016'],
    storageTipFr: 'Conserver au réfrigérateur pour préserver sa texture.',
    storageTipEn: 'Refrigerate to prevent skin and flesh from turning mealy.',
    freezerTipFr: 'Trancher et congeler pour compotes douces.',
    freezerTipEn: 'Slice and freeze for naturally sweet sauces.',
    nutritionSummary: '52 kcal • Riche en polyphénols',
  },
  'royal-gala': {
    id: 'royal-gala',
    className: 'Royal-Gala',
    nameFr: 'Pomme Royal Gala croquante',
    nameEn: 'Royal Gala Apple',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 25,
    pluCode: '4135',
    calories: 53,
    originFr: 'Canada No. 1 • PLU #4135',
    originEn: 'Canada No. 1 • PLU #4135',
    brand: 'Vergers du Québec',
    packagingFormatFr: 'Fruit frais en vrac',
    packagingFormatEn: 'Fresh loose produce',
    dietaryBadges: ['Produits frais', 'Code PLU #4135', 'Aliments du Québec'],
    storageTipFr: 'Conserver au bac à légumes pour conserver toute sa douceur parfumée.',
    storageTipEn: 'Store in crisper drawer for aromatic sweet bite.',
    freezerTipFr: 'Congeler pelée en dés pour tartes et gâteaux.',
    freezerTipEn: 'Peel, dice and freeze for pies and cakes.',
    nutritionSummary: '53 kcal • Saveur florale douce',
  },
  avocado: {
    id: 'avocado',
    className: 'Avocado',
    nameFr: 'Avocat Hass mûr et crémeux',
    nameEn: 'Ripe Hass Avocado',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 6,
    pluCode: '4046',
    calories: 160,
    originFr: 'Importé • Pastille PLU #4046 (Mexique)',
    originEn: 'Imported • PLU Sticker #4046 (Mexico)',
    brand: 'Avocats du Mexique',
    packagingFormatFr: 'Fruit frais en vrac',
    packagingFormatEn: 'Fresh loose produce',
    dietaryBadges: ['Produits frais', 'Code PLU #4046', 'Bons gras oméga-9'],
    storageTipFr: 'Laisser mûrir sur le comptoir. Placer au réfrigérateur une fois souple sous le pouce.',
    storageTipEn: 'Ripen at room temperature. Refrigerate once skin yields slightly to thumb pressure.',
    freezerTipFr: 'Écraser avec du jus de lime et congeler en purée hermétique pour guacamole.',
    freezerTipEn: 'Mash with fresh lime juice and freeze in an airtight pouch for guacamole.',
    nutritionSummary: '160 kcal • Riche en acides gras mono-insaturés et potassium',
  },
  banana: {
    id: 'banana',
    className: 'Banana',
    nameFr: 'Bananes jaunes fraîches',
    nameEn: 'Fresh Yellow Bananas',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 6,
    pluCode: '4011',
    calories: 89,
    originFr: 'Pastille PLU #4011 (Costa Rica / Équateur)',
    originEn: 'PLU Sticker #4011 (Central America)',
    brand: 'Sélection Fruits Frais',
    packagingFormatFr: 'Régime de bananes en vrac',
    packagingFormatEn: 'Fresh loose banana cluster',
    dietaryBadges: ['Produits frais', 'Code PLU #4011', 'Source de potassium'],
    storageTipFr: 'Conserver à l’air libre sur le comptoir à l’abri du soleil direct. Ne pas réfrigérer vertes.',
    storageTipEn: 'Store on countertop away from direct sunlight. Do not refrigerate while green.',
    freezerTipFr: 'Peler, tronçonner en rondelles et congeler en sachet pour smoothies et Nice Cream.',
    freezerTipEn: 'Peel, slice into discs, and freeze in ziplock bags for smoothies and banana bread.',
    nutritionSummary: '89 kcal • Riche en potassium et vitamine B6',
  },
  kiwi: {
    id: 'kiwi',
    className: 'Kiwi',
    nameFr: 'Kiwi vert frais (Hayward)',
    nameEn: 'Fresh Green Kiwi (Hayward)',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 14,
    pluCode: '4030',
    calories: 61,
    originFr: 'Pastille PLU #4030',
    originEn: 'PLU Sticker #4030',
    brand: 'Sélection Fruits Frais',
    packagingFormatFr: 'Fruit frais en vrac',
    packagingFormatEn: 'Fresh loose produce',
    dietaryBadges: ['Produits frais', 'Code PLU #4030', 'Riche en vitamine C'],
    storageTipFr: 'Conserver au réfrigérateur une fois mûr. Se conserve plusieurs semaines.',
    storageTipEn: 'Keep refrigerated once ripe. Lasts several weeks in the crisper.',
    freezerTipFr: 'Peler, couper en rondelles et congeler sur plaque pour garnitures.',
    freezerTipEn: 'Peel, slice and freeze flat on parchment for smoothies.',
    nutritionSummary: '61 kcal • Exceptionnelle teneur en vitamine C',
  },
  lemon: {
    id: 'lemon',
    className: 'Lemon',
    nameFr: 'Citrons jaunes frais',
    nameEn: 'Fresh Yellow Lemons',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 21,
    pluCode: '4053',
    calories: 29,
    originFr: 'Pastille PLU #4053',
    originEn: 'PLU Sticker #4053',
    brand: 'Agrumes Sélection',
    packagingFormatFr: 'Agrumes frais en vrac',
    packagingFormatEn: 'Fresh loose citrus',
    dietaryBadges: ['Produits frais', 'Code PLU #4053', 'Vitamine C'],
    storageTipFr: 'Placer dans un contenant d’eau ou au bac à légumes pour conserver le jus pendant 3-4 semaines.',
    storageTipEn: 'Store in the crisper drawer or in a sealed container for optimal juiciness.',
    freezerTipFr: 'Presser le jus dans un bac à glaçons et râper le zeste avant congélation.',
    freezerTipEn: 'Juice into ice cube trays and freeze zest in small airtight jars.',
    nutritionSummary: '29 kcal • Concentré en acide citrique naturel & vitamine C',
  },
  lime: {
    id: 'lime',
    className: 'Lime',
    nameFr: 'Limes vertes fraîches (Citrons verts)',
    nameEn: 'Fresh Green Limes (Persian Limes)',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 18,
    pluCode: '4048',
    calories: 30,
    originFr: 'Pastille PLU #4048 (Mexique)',
    originEn: 'PLU Sticker #4048 (Mexico)',
    brand: 'Agrumes Sélection',
    packagingFormatFr: 'Agrumes frais en vrac',
    packagingFormatEn: 'Fresh loose citrus',
    dietaryBadges: ['Produits frais', 'Code PLU #4048'],
    storageTipFr: 'Conserver au réfrigérateur pour éviter que la peau ne durcisse.',
    storageTipEn: 'Keep in the crisper drawer to prevent skin from drying out.',
    freezerTipFr: 'Congeler le jus pressé en cubes pour cocktails et marinades.',
    freezerTipEn: 'Freeze freshly squeezed juice in ice cube trays for marinades and cocktails.',
    nutritionSummary: '30 kcal • Idéal pour assaisonnements et guacamole',
  },
  mango: {
    id: 'mango',
    className: 'Mango',
    nameFr: 'Mangue rouge fraîche (Tommy Atkins / Kent)',
    nameEn: 'Fresh Red Mango (Tommy Atkins / Kent)',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 7,
    pluCode: '4051',
    calories: 60,
    originFr: 'No. 1 • Pastille PLU #4051 (Mexique / Brésil)',
    originEn: 'No. 1 • PLU Sticker #4051 (Imported)',
    brand: 'Sélection Fruits Frais',
    packagingFormatFr: 'Fruit frais en vrac',
    packagingFormatEn: 'Fresh loose produce',
    dietaryBadges: ['Produits frais', 'Code PLU #4051', 'Vitamine A & C'],
    storageTipFr: 'Mûrir à température ambiante sur le comptoir. Transférer au réfrigérateur une fois souple et parfumée.',
    storageTipEn: 'Ripen at room temperature on counter. Move to fridge once aromatic and yielding to gentle touch.',
    freezerTipFr: 'Peler, trancher la chair en dés autour du noyau plat et congeler sur une plaque pour smoothies.',
    freezerTipEn: 'Peel, dice flesh around flat stone, and freeze flat on a parchment tray for smoothies.',
    nutritionSummary: '60 kcal • Douce, sucrée et antioxydante',
  },
  cantaloupe: {
    id: 'cantaloupe',
    className: 'Cantaloupe',
    nameFr: 'Melon cantaloup sucré à chair orangée',
    nameEn: 'Sweet Orange Cantaloupe Melon',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 6,
    pluCode: '4050',
    calories: 34,
    originFr: 'No. 1 • Pastille PLU #4050',
    originEn: 'No. 1 • PLU Sticker #4050',
    brand: 'Sélection Melons',
    packagingFormatFr: 'Melon entier en vrac',
    packagingFormatEn: 'Whole fresh melon',
    dietaryBadges: ['Produits frais', 'Code PLU #4050', 'Bêta-carotène'],
    storageTipFr: 'Mûrir à l’air libre. Une fois coupé, recouvrir de pellicule et réfrigérer.',
    storageTipEn: 'Ripen on counter. Once sliced, wrap securely and refrigerate immediately.',
    freezerTipFr: 'Façonner des billes à la cuillère parisienne et congeler pour cocktails ou salades.',
    freezerTipEn: 'Scoop into melon balls and freeze on a tray for smoothies and summer drinks.',
    nutritionSummary: '34 kcal • Hydratant et gorgé de caroténoïdes',
  },
  'galia-melon': {
    id: 'galia-melon',
    className: 'Galia-Melon',
    nameFr: 'Melon Galia parfumé à chair verte',
    nameEn: 'Galia Green Flesh Melon',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 6,
    calories: 32,
    originFr: 'Sélection Melons doux',
    originEn: 'Sweet Melon Selection',
    brand: 'Sélection Fruits',
    packagingFormatFr: 'Melon entier en vrac',
    packagingFormatEn: 'Whole fresh melon',
    dietaryBadges: ['Produits frais'],
    storageTipFr: 'Conserver sur le comptoir jusqu’à maturité parfumée, puis réfrigérer.',
    storageTipEn: 'Keep at room temperature until sweet aroma develops, then refrigerate.',
    freezerTipFr: 'Couper en cubes et congeler sous vide pour smoothies.',
    freezerTipEn: 'Cube flesh and freeze in airtight bags for smoothies.',
    nutritionSummary: '32 kcal • Parfum tropical rafraîchissant',
  },
  'honeydew-melon': {
    id: 'honeydew-melon',
    className: 'Honeydew-Melon',
    nameFr: 'Melon miel à chair verte claire',
    nameEn: 'Honeydew Melon',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 7,
    pluCode: '4329',
    calories: 36,
    originFr: 'No. 1 • PLU #4329',
    originEn: 'No. 1 • PLU #4329',
    brand: 'Sélection Melons',
    packagingFormatFr: 'Melon entier en vrac',
    packagingFormatEn: 'Whole fresh melon',
    dietaryBadges: ['Produits frais', 'Code PLU #4329'],
    storageTipFr: 'Conserver entier à température ambiante, puis réfrigérer une fois entamé.',
    storageTipEn: 'Store whole at room temperature, refrigerate tightly wrapped once cut.',
    freezerTipFr: 'Congeler en tranches ou cubes pour sorbets maison.',
    freezerTipEn: 'Freeze in cubes for refreshing homemade sorbets.',
    nutritionSummary: '36 kcal • Hydratation maximale et douceur subtile',
  },
  watermelon: {
    id: 'watermelon',
    className: 'Watermelon',
    nameFr: 'Melon d’eau frais (Pastèque sans pépins)',
    nameEn: 'Fresh Seedless Watermelon',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 8,
    pluCode: '4032',
    calories: 30,
    originFr: 'Pastille PLU #4032 / #3421',
    originEn: 'PLU Sticker #4032 / #3421',
    brand: 'Sélection Fruits d’été',
    packagingFormatFr: 'Melon entier ou demie-pièce',
    packagingFormatEn: 'Whole or halved melon',
    dietaryBadges: ['Produits frais', 'Code PLU #4032', 'Lycopène'],
    storageTipFr: 'Conserver entier au frais ou tempéré. Une fois tranché, réfrigérer hermétiquement.',
    storageTipEn: 'Keep whole at cool room temp. Once sliced, wrap tightly and store in fridge.',
    freezerTipFr: 'Couper en dés et congeler comme glaçons naturels pour eaux aromatisées.',
    freezerTipEn: 'Cut into bite-sized cubes and freeze as natural ice cubes for summer beverages.',
    nutritionSummary: '30 kcal • Composé à 92% d’eau naturelle riche en lycopène',
  },
  nectarine: {
    id: 'nectarine',
    className: 'Nectarine',
    nameFr: 'Nectarines fraîches à peau lisse',
    nameEn: 'Fresh Sweet Nectarines',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 5,
    pluCode: '4036',
    calories: 44,
    originFr: 'Pastille PLU #4036',
    originEn: 'PLU Sticker #4036',
    brand: 'Fruits de vergers',
    packagingFormatFr: 'Fruits à noyau en vrac',
    packagingFormatEn: 'Fresh stone fruit',
    dietaryBadges: ['Produits frais', 'Code PLU #4036'],
    storageTipFr: 'Mûrir sur le comptoir. Déplacer au réfrigérateur une fois tendre au toucher.',
    storageTipEn: 'Ripen stem-end down on counter. Refrigerate once yielding to gentle pressure.',
    freezerTipFr: 'Dénoyauter, trancher et congeler avec un soupçon de jus de citron.',
    freezerTipEn: 'Pit, slice and freeze in single layers with lemon juice.',
    nutritionSummary: '44 kcal • Riche en vitamines A et potassium',
  },
  orange: {
    id: 'orange',
    className: 'Orange',
    nameFr: 'Oranges douces Navel à jus',
    nameEn: 'Sweet Navel Oranges',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 21,
    pluCode: '4012',
    calories: 47,
    originFr: 'Pastille PLU #4012 (Californie / Floride)',
    originEn: 'PLU Sticker #4012',
    brand: 'Agrumes Sélection',
    packagingFormatFr: 'Agrumes en vrac ou sac',
    packagingFormatEn: 'Fresh loose citrus',
    dietaryBadges: ['Produits frais', 'Code PLU #4012', 'Source de vitamine C'],
    storageTipFr: 'Se conserve 3 semaines au bac à légumes du réfrigérateur.',
    storageTipEn: 'Keeps fresh for up to 3 weeks in the refrigerator crisper.',
    freezerTipFr: 'Peler, séparer les suprêmes et congeler en portions.',
    freezerTipEn: 'Peel, segment and freeze on trays for refreshing snacks.',
    nutritionSummary: '47 kcal • 100% de l’apport quotidien recommandé en vitamine C',
  },
  papaya: {
    id: 'papaya',
    className: 'Papaya',
    nameFr: 'Papaye tropicale fraîche',
    nameEn: 'Fresh Tropical Papaya',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 5,
    pluCode: '4394',
    calories: 43,
    originFr: 'Importé • PLU #4394',
    originEn: 'Imported • PLU #4394',
    brand: 'Fruits Tropicaux',
    packagingFormatFr: 'Fruit tropical en vrac',
    packagingFormatEn: 'Whole tropical fruit',
    dietaryBadges: ['Produits frais', 'Code PLU #4394'],
    storageTipFr: 'Mûrir sur le comptoir jusqu’à coloration jaune-orangée, puis réfrigérer.',
    storageTipEn: 'Ripen at room temperature until skin turns yellow, then refrigerate.',
    freezerTipFr: 'Égrainer, couper en dés et congeler pour smoothies digestifs (papaïne).',
    freezerTipEn: 'Scoop seeds, dice flesh and freeze for enzyme-rich smoothies.',
    nutritionSummary: '43 kcal • Riche en papaïne naturelle favorisant la digestion',
  },
  'passion-fruit': {
    id: 'passion-fruit',
    className: 'Passion-Fruit',
    nameFr: 'Fruits de la passion (Maracuja)',
    nameEn: 'Fresh Passion Fruit (Maracuja)',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 7,
    calories: 97,
    originFr: 'Importé Sélection Exotique',
    originEn: 'Exotic Selection',
    brand: 'Sélection Exotique',
    packagingFormatFr: 'Fruits exotiques en vrac',
    packagingFormatEn: 'Loose passion fruit',
    dietaryBadges: ['Produits frais'],
    storageTipFr: 'Idéal lorsque la peau devient légèrement fripée et ridée.',
    storageTipEn: 'At its sweetest when skin is wrinkled and fragrant.',
    freezerTipFr: 'Extraire la pulpe avec les graines et congeler dans un bac à glaçons.',
    freezerTipEn: 'Scoop aromatic pulp and freeze in ice cube trays for cocktails and desserts.',
    nutritionSummary: '97 kcal • Riche en fibres et arômes intenses',
  },
  peach: {
    id: 'peach',
    className: 'Peach',
    nameFr: 'Pêches fraîches juteuses',
    nameEn: 'Fresh Juicy Peaches',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 5,
    pluCode: '4038',
    calories: 39,
    originFr: 'Pastille PLU #4038 (Ontario / Québec)',
    originEn: 'PLU Sticker #4038',
    brand: 'Vergers Locaux',
    packagingFormatFr: 'Fruits à noyau en vrac',
    packagingFormatEn: 'Fresh stone fruit',
    dietaryBadges: ['Produits frais', 'Code PLU #4038'],
    storageTipFr: 'Laisser mûrir sur le comptoir sans les empiler. Réfrigérer dès qu’elles sont souples.',
    storageTipEn: 'Ripen on counter stem-side down. Refrigerate once aromatic and slightly soft.',
    freezerTipFr: 'Peler, couper en tranches et congeler avec un peu de jus de citron.',
    freezerTipEn: 'Blanch to peel, slice and freeze in vacuum bags for crumbles.',
    nutritionSummary: '39 kcal • Délicate douceur estivale',
  },
  anjou: {
    id: 'anjou',
    className: 'Anjou',
    nameFr: 'Poires Anjou vertes fraîches',
    nameEn: 'Fresh Green Anjou Pears',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 10,
    pluCode: '4416',
    calories: 57,
    originFr: 'Canada No. 1 • PLU #4416',
    originEn: 'Canada No. 1 • PLU #4416',
    brand: 'Sélection Poires',
    packagingFormatFr: 'Fruit frais en vrac',
    packagingFormatEn: 'Fresh loose produce',
    dietaryBadges: ['Produits frais', 'Code PLU #4416'],
    storageTipFr: 'Vérifier la souplesse près de la queue. Réfrigérer pour ralentir le mûrissement.',
    storageTipEn: 'Check the neck for ripeness. Move to fridge once it yields slightly.',
    freezerTipFr: 'Pocher légèrement au sirop léger avant de congeler.',
    freezerTipEn: 'Poach lightly in light syrup before freezing for desserts.',
    nutritionSummary: '57 kcal • Riche en fibres solubles',
  },
  conference: {
    id: 'conference',
    className: 'Conference',
    nameFr: 'Poires Conférence parfumées',
    nameEn: 'Conference Pears',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 10,
    calories: 56,
    originFr: 'Sélection Poires douces',
    originEn: 'Sweet Pear Selection',
    brand: 'Sélection Poires',
    packagingFormatFr: 'Fruit frais en vrac',
    packagingFormatEn: 'Fresh loose produce',
    dietaryBadges: ['Produits frais'],
    storageTipFr: 'Conserver à température ambiante, puis réfrigérer une fois fondantes.',
    storageTipEn: 'Keep at room temp, refrigerate once neck yields.',
    freezerTipFr: 'Trancher et congeler pour tartes et clafoutis.',
    freezerTipEn: 'Slice and freeze for pies and crumbles.',
    nutritionSummary: '56 kcal • Chair fondante et juteuse',
  },
  kaiser: {
    id: 'kaiser',
    className: 'Kaiser',
    nameFr: 'Poires Bosc / Kaiser rousses',
    nameEn: 'Bosc / Kaiser Russet Pears',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 12,
    pluCode: '4413',
    calories: 58,
    originFr: 'Canada No. 1 • PLU #4413',
    originEn: 'Canada No. 1 • PLU #4413',
    brand: 'Sélection Poires',
    packagingFormatFr: 'Fruit frais en vrac',
    packagingFormatEn: 'Fresh loose produce',
    dietaryBadges: ['Produits frais', 'Code PLU #4413'],
    storageTipFr: 'Idéale pour la cuisson, conserve sa fermeté. Conserver au frais.',
    storageTipEn: 'Ideal for poaching and baking, retains shape well. Store cool.',
    freezerTipFr: 'Peler, couper en deux, évider et congeler pour poires pochées.',
    freezerTipEn: 'Peel, halve, core and freeze for poached pear desserts.',
    nutritionSummary: '58 kcal • Excellente tenue en pâtisserie',
  },
  pineapple: {
    id: 'pineapple',
    className: 'Pineapple',
    nameFr: 'Ananas frais doré (Golden Ripe)',
    nameEn: 'Golden Ripe Fresh Pineapple',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 6,
    pluCode: '4430',
    calories: 50,
    originFr: 'Pastille PLU #4430 (Costa Rica)',
    originEn: 'PLU Sticker #4430 (Costa Rica)',
    brand: 'Sélection Fruits Tropicaux',
    packagingFormatFr: 'Ananas entier avec couronne',
    packagingFormatEn: 'Whole fresh pineapple',
    dietaryBadges: ['Produits frais', 'Code PLU #4430', 'Bromélaïne'],
    storageTipFr: 'Conserver entier sur le comptoir 2-3 jours. Une fois paré et coupé, conserver au réfrigérateur.',
    storageTipEn: 'Store whole at room temperature for up to 3 days. Once trimmed and chunked, keep chilled in an airtight bowl.',
    freezerTipFr: 'Couper en dés et congeler sur plaque pour cocktails et smoothies.',
    freezerTipEn: 'Freeze trimmed chunks in single layer on parchment for smoothies.',
    nutritionSummary: '50 kcal • Source de bromélaïne facilitant la digestion',
  },
  plum: {
    id: 'plum',
    className: 'Plum',
    nameFr: 'Prunes fraîches violettes / rouges',
    nameEn: 'Fresh Purple / Red Plums',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 6,
    pluCode: '4040',
    calories: 46,
    originFr: 'Pastille PLU #4040',
    originEn: 'PLU Sticker #4040',
    brand: 'Vergers Locaux',
    packagingFormatFr: 'Fruits à noyau en vrac',
    packagingFormatEn: 'Fresh stone fruit',
    dietaryBadges: ['Produits frais', 'Code PLU #4040'],
    storageTipFr: 'Mûrir à l’air libre sur le comptoir. Réfrigérer une fois douces au toucher.',
    storageTipEn: 'Ripen at room temperature, refrigerate once soft.',
    freezerTipFr: 'Couper en deux, dénoyauter et congeler à plat.',
    freezerTipEn: 'Halve, pit and freeze flat for plum crumbles and jams.',
    nutritionSummary: '46 kcal • Riche en antioxydants et fibres',
  },
  pomegranate: {
    id: 'pomegranate',
    className: 'Pomegranate',
    nameFr: 'Grenade fraîche à arilles rubis',
    nameEn: 'Fresh Wonderful Pomegranate',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 30,
    pluCode: '4445',
    calories: 83,
    originFr: 'Pastille PLU #4445',
    originEn: 'PLU Sticker #4445',
    brand: 'Fruits d’Automne',
    packagingFormatFr: 'Grenade entière en vrac',
    packagingFormatEn: 'Whole fresh pomegranate',
    dietaryBadges: ['Produits frais', 'Code PLU #4445', 'Polyphénols'],
    storageTipFr: 'Conserver entière au réfrigérateur jusqu’à un mois.',
    storageTipEn: 'Stores well whole in the refrigerator up to a month.',
    freezerTipFr: 'Égrener dans un bol d’eau, sécher les arilles et congeler en sachet.',
    freezerTipEn: 'Extract seeds in water, pat dry, and freeze seeds in single layer.',
    nutritionSummary: '83 kcal • Puissant antioxydant naturel',
  },
  'red-grapefruit': {
    id: 'red-grapefruit',
    className: 'Red-Grapefruit',
    nameFr: 'Pamplemousse rouge / rose de Floride',
    nameEn: 'Red / Pink Florida Grapefruit',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 21,
    pluCode: '4288',
    calories: 42,
    originFr: 'Pastille PLU #4288 (Floride / Texas)',
    originEn: 'PLU Sticker #4288',
    brand: 'Agrumes Sélection',
    packagingFormatFr: 'Agrumes en vrac',
    packagingFormatEn: 'Fresh loose citrus',
    dietaryBadges: ['Produits frais', 'Code PLU #4288', 'Vitamine C & Lycopène'],
    storageTipFr: 'Conserver au tiroir à fruits du réfrigérateur pour préserver toute sa jutosité.',
    storageTipEn: 'Keep in crisper drawer for maximum juiciness.',
    freezerTipFr: 'Presser le jus et congeler en portions ou bacs à glaçons.',
    freezerTipEn: 'Juice and freeze in cube trays for vinaigrettes and drinks.',
    nutritionSummary: '42 kcal • Rafraîchissant, riche en flavonoïdes',
  },
  satsumas: {
    id: 'satsumas',
    className: 'Satsumas',
    nameFr: 'Mandarines Satsuma faciles à peler',
    nameEn: 'Easy-Peel Satsuma Mandarins',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 14,
    pluCode: '4427',
    calories: 44,
    originFr: 'Pastille PLU #4427',
    originEn: 'PLU Sticker #4427',
    brand: 'Agrumes Doux',
    packagingFormatFr: 'Mandarines en filet ou vrac',
    packagingFormatEn: 'Net bag or loose mandarins',
    dietaryBadges: ['Produits frais', 'Code PLU #4427'],
    storageTipFr: 'Conserver au frais. Très facile à peler sans couteau.',
    storageTipEn: 'Keep cool. Zipper-skin makes them easy to peel.',
    freezerTipFr: 'Peler et congeler les quartiers pour collations givrées.',
    freezerTipEn: 'Peel and freeze segments for frosty fruit snacks.',
    nutritionSummary: '44 kcal • Idéale pour les collations',
  },
  asparagus: {
    id: 'asparagus',
    className: 'Asparagus',
    nameFr: 'Asperges vertes fraîches croquantes',
    nameEn: 'Fresh Green Crisp Asparagus',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 7,
    pluCode: '4080',
    calories: 20,
    originFr: 'No. 1 • PLU #4080 (Québec / Ontario)',
    originEn: 'Canada No. 1 • PLU #4080',
    brand: 'Maraîchers Locaux',
    packagingFormatFr: 'Botte d’asperges avec élastique',
    packagingFormatEn: 'Fresh banded bunch',
    dietaryBadges: ['Produits frais', 'Code PLU #4080', 'Folate & Fer'],
    storageTipFr: 'Placer les tiges debout dans un verre avec 2 cm d’eau au réfrigérateur.',
    storageTipEn: 'Stand stalks upright in a glass with 1 inch of water in the fridge like flowers.',
    freezerTipFr: 'Blanchir 2 minutes à l’eau bouillante, refroidir dans l’eau glacée et congeler.',
    freezerTipEn: 'Blanch in boiling water 2 mins, ice shock, dry thoroughly and freeze.',
    nutritionSummary: '20 kcal • Très faible en calories, riche en folates',
  },
  aubergine: {
    id: 'aubergine',
    className: 'Aubergine',
    nameFr: 'Aubergine fraîche violette brillante',
    nameEn: 'Fresh Purple Globe Eggplant',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 7,
    pluCode: '4081',
    calories: 25,
    originFr: 'No. 1 • Pastille PLU #4081',
    originEn: 'No. 1 • PLU Sticker #4081',
    brand: 'Maraîchers Locaux',
    packagingFormatFr: 'Légume frais en vrac',
    packagingFormatEn: 'Fresh loose produce',
    dietaryBadges: ['Produits frais', 'Code PLU #4081'],
    storageTipFr: 'Sensible au froid extrême : placer au bac à légumes du réfrigérateur et cuisiner rapidement.',
    storageTipEn: 'Keep in crisper drawer and prepare within 5-7 days.',
    freezerTipFr: 'Trancher, griller ou cuire au four avant de congeler pour ratatouilles et moussakas.',
    freezerTipEn: 'Slice, brush with oil, roast and freeze flat for casseroles.',
    nutritionSummary: '25 kcal • Chair fondante gorgée de fibres',
  },
  cabbage: {
    id: 'cabbage',
    className: 'Cabbage',
    nameFr: 'Chou vert frais du Québec',
    nameEn: 'Fresh Green Cabbage',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 30,
    pluCode: '4069',
    calories: 25,
    originFr: 'Légumes de garde du Québec • PLU #4069',
    originEn: 'Locally grown green cabbage • PLU #4069',
    brand: 'Maraîchers du Québec',
    packagingFormatFr: 'Chou entier en vrac',
    packagingFormatEn: 'Whole cabbage head',
    dietaryBadges: ['Produits frais', 'Code PLU #4069', 'Aliments du Québec'],
    storageTipFr: 'Excellente conservation jusqu’à un mois au bac à légumes du réfrigérateur.',
    storageTipEn: 'Keeps for over a month in the refrigerator crisper.',
    freezerTipFr: 'Émincer, blanchir 1 minute et congeler en portions pour soupes.',
    freezerTipEn: 'Shred, blanch 1 minute, cool and freeze in bags for stews.',
    nutritionSummary: '25 kcal • Champion de la conservation et de la vitamine K',
  },
  carrots: {
    id: 'carrots',
    className: 'Carrots',
    nameFr: 'Carottes fraîches du Québec',
    nameEn: 'Fresh Local Carrots',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 30,
    pluCode: '4562',
    calories: 41,
    originFr: 'Terre noire du Québec No. 1 • PLU #4562',
    originEn: 'Canada No. 1 Carrots',
    brand: 'Maraîchers du Québec',
    packagingFormatFr: 'Sac de 3 lb ou carottes en vrac',
    packagingFormatEn: '3 lb bag or loose carrots',
    dietaryBadges: ['Produits frais', 'Code PLU #4562', 'Aliments du Québec', 'Bêta-carotène'],
    storageTipFr: 'Conserver au réfrigérateur dans un sachet perforé pour éviter la condensation.',
    storageTipEn: 'Store in vegetable crisper in a perforated bag to prevent moisture buildup.',
    freezerTipFr: 'Peler, couper en rondelles, blanchir 2 minutes et congeler.',
    freezerTipEn: 'Peel, coin cut, blanch 2 minutes and freeze in portions.',
    nutritionSummary: '41 kcal • Concentré naturel de provitamine A',
  },
  cucumber: {
    id: 'cucumber',
    className: 'Cucumber',
    nameFr: 'Concombre anglais sans pépins',
    nameEn: 'Seedless English Cucumber',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 9,
    pluCode: '4593',
    calories: 15,
    originFr: 'Serres du Québec No. 1 • PLU #4593',
    originEn: 'Greenhouse English Cucumber (PLU #4593)',
    brand: 'Serres du Québec',
    packagingFormatFr: 'Emballé sous pellicule plastique protectrice',
    packagingFormatEn: 'Individually plastic wrapped',
    dietaryBadges: ['Produits frais', 'Code PLU #4593', 'Aliments du Québec'],
    storageTipFr: 'Laisser la pellicule plastique jusqu’à utilisation pour retenir l’humidité.',
    storageTipEn: 'Leave in plastic wrap until ready to slice to lock in freshness.',
    freezerTipFr: 'Non recommandé pour la congélation crue ; idéal en potage froid mixé.',
    freezerTipEn: 'Not recommended for raw freezing; purée for chilled gazpachos.',
    nutritionSummary: '15 kcal • Ultra-hydratant et rafraîchissant',
  },
  garlic: {
    id: 'garlic',
    className: 'Garlic',
    nameFr: 'Ail blanc en bulbes',
    nameEn: 'Fresh Garlic Bulbs',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 60,
    pluCode: '4608',
    calories: 149,
    originFr: 'Bulbes séchés No. 1',
    originEn: 'Fresh cured garlic bulbs',
    brand: 'Ail Sélection',
    packagingFormatFr: 'Bulbes en filet ou vrac',
    packagingFormatEn: 'Net mesh bag or loose bulbs',
    dietaryBadges: ['Produits frais', 'Code PLU #4608'],
    storageTipFr: 'Conserver dans un endroit sec, sombre et ventilé dans le garde-manger. Ne jamais réfrigérer.',
    storageTipEn: 'Store in a dry, ventilated, dark pantry spot. Never refrigerate whole bulbs.',
    freezerTipFr: 'Éplucher les gousses et congeler entières dans un petit bocal hermétique.',
    freezerTipEn: 'Peel individual cloves and freeze whole in a small glass jar.',
    nutritionSummary: '149 kcal • Riche en allicine et composés aromatiques',
  },
  ginger: {
    id: 'ginger',
    className: 'Ginger',
    nameFr: 'Racine de gingembre frais',
    nameEn: 'Fresh Ginger Root',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 28,
    pluCode: '4612',
    calories: 80,
    originFr: 'Rhizome frais • PLU #4612',
    originEn: 'Fresh rhizome • PLU #4612',
    brand: 'Épices & Racines',
    packagingFormatFr: 'Rhizome frais en vrac',
    packagingFormatEn: 'Fresh loose root',
    dietaryBadges: ['Produits frais', 'Code PLU #4612'],
    storageTipFr: 'Conserver au réfrigérateur dans un sachet réutilisable.',
    storageTipEn: 'Store unpeeled in a reusable bag in the crisper drawer.',
    freezerTipFr: 'Congeler la racine entière non pelée et râper directement gelée à la microplane.',
    freezerTipEn: 'Freeze whole unpeeled root and grate directly from frozen on a microplane.',
    nutritionSummary: '80 kcal • Puissant tonique naturel et gingérols',
  },
  leek: {
    id: 'leek',
    className: 'Leek',
    nameFr: 'Poireaux frais du Québec',
    nameEn: 'Fresh Local Leeks',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 14,
    pluCode: '4629',
    calories: 61,
    originFr: 'Maraîchers du Québec • PLU #4629',
    originEn: 'Canada No. 1 Leeks',
    brand: 'Maraîchers du Québec',
    packagingFormatFr: 'Botte de poireaux frais',
    packagingFormatEn: 'Fresh bunch of leeks',
    dietaryBadges: ['Produits frais', 'Code PLU #4629', 'Aliments du Québec'],
    storageTipFr: 'Conserver non lavé au bac à légumes du réfrigérateur.',
    storageTipEn: 'Store unwashed in the crisper drawer.',
    freezerTipFr: 'Trancher en rondelles, rincer à grande eau, essorer et congeler.',
    freezerTipEn: 'Slice into rings, wash out grit thoroughly, dry and freeze in bags.',
    nutritionSummary: '61 kcal • Délicat goût d’oignon doux et fibres prébiotiques',
  },
  'brown-cap-mushroom': {
    id: 'brown-cap-mushroom',
    className: 'Brown-Cap-Mushroom',
    nameFr: 'Champignons Cremini bruns frais',
    nameEn: 'Fresh Cremini / Brown Mushrooms',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 7,
    pluCode: '4648',
    calories: 22,
    originFr: 'Champignons du Canada • PLU #4648',
    originEn: 'Fresh Canadian Mushrooms (PLU #4648)',
    brand: 'Champignons Sélection',
    packagingFormatFr: 'Barquette carton ou vrac',
    packagingFormatEn: 'Paper bag or recyclable punnet',
    dietaryBadges: ['Produits frais', 'Code PLU #4648', 'Vitamine D & Minéraux'],
    storageTipFr: 'Conserver dans un sac en papier au réfrigérateur pour éviter l’humidité.',
    storageTipEn: 'Store in a breathable paper bag in the fridge to prevent sliminess.',
    freezerTipFr: 'Sauter à la poêle avec un filet d’huile avant de congeler.',
    freezerTipEn: 'Sauté with a touch of oil first, cool and freeze in portions.',
    nutritionSummary: '22 kcal • Saveur umami naturelle riche en sélénium',
  },
  'yellow-onion': {
    id: 'yellow-onion',
    className: 'Yellow-Onion',
    nameFr: 'Oignons jaunes de garde du Québec',
    nameEn: 'Fresh Yellow Cooking Onions',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 45,
    pluCode: '4093',
    calories: 40,
    originFr: 'Terre noire du Québec No. 1 • PLU #4093',
    originEn: 'Canada No. 1 Yellow Onions',
    brand: 'Maraîchers du Québec',
    packagingFormatFr: 'Sac de 2 lb/5 lb ou vrac',
    packagingFormatEn: 'Mesh bag or loose onions',
    dietaryBadges: ['Produits frais', 'Code PLU #4093', 'Aliments du Québec'],
    storageTipFr: 'Conserver dans un endroit frais, sec et sombre du garde-manger. Éloigner des pommes de terre.',
    storageTipEn: 'Store in a cool, dry, dark pantry basket away from potatoes.',
    freezerTipFr: 'Hacher et congeler à plat en sachet pour utilisation directe dans les poêlées.',
    freezerTipEn: 'Chop and freeze flat in ziplock bags for quick soup & sauté starters.',
    nutritionSummary: '40 kcal • Base aromatique indispensable riche en quercétine',
  },
  'green-bell-pepper': {
    id: 'green-bell-pepper',
    className: 'Green-Bell-Pepper',
    nameFr: 'Poivron vert doux croquant',
    nameEn: 'Fresh Crisp Green Bell Pepper',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 10,
    pluCode: '4065',
    calories: 20,
    originFr: 'Serres du Québec No. 1 • PLU #4065',
    originEn: 'Canada No. 1 Bell Pepper',
    brand: 'Serres du Québec',
    packagingFormatFr: 'Poivron frais en vrac',
    packagingFormatEn: 'Fresh loose pepper',
    dietaryBadges: ['Produits frais', 'Code PLU #4065', 'Aliments du Québec'],
    storageTipFr: 'Conserver au bac à légumes du réfrigérateur.',
    storageTipEn: 'Keep in refrigerator crisper drawer.',
    freezerTipFr: 'Épépiner, couper en lanières et congeler sans blanchiment préalable.',
    freezerTipEn: 'Core, seed, slice into strips and freeze raw on baking sheet.',
    nutritionSummary: '20 kcal • Croquant rafraîchissant riche en vitamine C',
  },
  'orange-bell-pepper': {
    id: 'orange-bell-pepper',
    className: 'Orange-Bell-Pepper',
    nameFr: 'Poivron orange doux et sucré',
    nameEn: 'Sweet Orange Bell Pepper',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 10,
    pluCode: '4688',
    calories: 28,
    originFr: 'Serres locales • PLU #4688',
    originEn: 'Canada No. 1 Bell Pepper',
    brand: 'Serres du Québec',
    packagingFormatFr: 'Poivron frais en vrac',
    packagingFormatEn: 'Fresh loose pepper',
    dietaryBadges: ['Produits frais', 'Code PLU #4688'],
    storageTipFr: 'Conserver au bac à légumes du réfrigérateur.',
    storageTipEn: 'Store in the crisper drawer.',
    freezerTipFr: 'Couper en dés et congeler en portions pour fajitas.',
    freezerTipEn: 'Dice and freeze for fajitas, omelettes and sauces.',
    nutritionSummary: '28 kcal • Saveur fruitée très douce',
  },
  'red-bell-pepper': {
    id: 'red-bell-pepper',
    className: 'Red-Bell-Pepper',
    nameFr: 'Poivron rouge doux mûr',
    nameEn: 'Ripe Red Bell Pepper',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 10,
    pluCode: '4088',
    calories: 31,
    originFr: 'Serres du Québec • PLU #4088',
    originEn: 'Canada No. 1 Red Bell Pepper',
    brand: 'Serres du Québec',
    packagingFormatFr: 'Poivron frais en vrac',
    packagingFormatEn: 'Fresh loose pepper',
    dietaryBadges: ['Produits frais', 'Code PLU #4088', 'Aliments du Québec'],
    storageTipFr: 'Conserver au frais dans le tiroir à légumes.',
    storageTipEn: 'Keep refrigerated in the crisper.',
    freezerTipFr: 'Griller au four, peler et congeler en lanières marinées.',
    freezerTipEn: 'Roast, peel and freeze in strips for pasta and sandwiches.',
    nutritionSummary: '31 kcal • Record de vitamine C (deux fois plus qu’une orange)',
  },
  'yellow-bell-pepper': {
    id: 'yellow-bell-pepper',
    className: 'Yellow-Bell-Pepper',
    nameFr: 'Poivron jaune doux ensoleillé',
    nameEn: 'Sunny Yellow Bell Pepper',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 10,
    pluCode: '4689',
    calories: 27,
    originFr: 'Serres locales • PLU #4689',
    originEn: 'Canada No. 1 Bell Pepper',
    brand: 'Serres du Québec',
    packagingFormatFr: 'Poivron frais en vrac',
    packagingFormatEn: 'Fresh loose pepper',
    dietaryBadges: ['Produits frais', 'Code PLU #4689'],
    storageTipFr: 'Conserver au bac à légumes.',
    storageTipEn: 'Keep in crisper drawer.',
    freezerTipFr: 'Couper en lanières et congeler à plat.',
    freezerTipEn: 'Slice into strips and freeze in single layers.',
    nutritionSummary: '27 kcal • Doux et croquant',
  },
  'floury-potato': {
    id: 'floury-potato',
    className: 'Floury-Potato',
    nameFr: 'Pommes de terre à chair farineuse (Russet / Pâtissière)',
    nameEn: 'Russet Baking Potatoes',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 30,
    pluCode: '4072',
    calories: 77,
    originFr: 'Terre agricole du Québec No. 1 • PLU #4072',
    originEn: 'Canada No. 1 Russet Potatoes',
    brand: 'Producteurs Locaux',
    packagingFormatFr: 'Sac de 5 lb ou 10 lb',
    packagingFormatEn: '5 lb or 10 lb potato bag',
    dietaryBadges: ['Produits frais', 'Code PLU #4072', 'Aliments du Québec'],
    storageTipFr: 'Conserver dans un endroit sombre, frais et bien aéré. Ne jamais réfrigérer cru.',
    storageTipEn: 'Store in a cool, dark, well-ventilated pantry bin. Never refrigerate raw potatoes.',
    freezerTipFr: 'Cuire en purée ou blanchir les frites avant de congeler.',
    freezerTipEn: 'Par-cook or mash completely before freezing; raw potatoes turn watery.',
    nutritionSummary: '77 kcal • Idéale pour purées légères et frites croustillantes',
  },
  'solid-potato': {
    id: 'solid-potato',
    className: 'Solid-Potato',
    nameFr: 'Pommes de terre à chair ferme (Rondes jaunes / Yukon Gold)',
    nameEn: 'Firm Yellow Potatoes (Yukon Gold)',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 30,
    pluCode: '4727',
    calories: 70,
    originFr: 'Pommes de terre jaunes du Québec • PLU #4727',
    originEn: 'Canada No. 1 Yellow Potatoes',
    brand: 'Maraîchers du Québec',
    packagingFormatFr: 'Sac de 5 lb / 10 lb',
    packagingFormatEn: '5 lb / 10 lb mesh bag',
    dietaryBadges: ['Produits frais', 'Code PLU #4727', 'Aliments du Québec'],
    storageTipFr: 'Conserver au garde-manger à l’abri de la lumière pour éviter le verdissement.',
    storageTipEn: 'Store in a dark pantry bin away from light to prevent greening.',
    freezerTipFr: 'Cuire à la vapeur, trancher et congeler pour rissoler.',
    freezerTipEn: 'Boil or steam till tender, slice and freeze for home fries.',
    nutritionSummary: '70 kcal • Texture beurrée naturelle',
  },
  'sweet-potato': {
    id: 'sweet-potato',
    className: 'Sweet-Potato',
    nameFr: 'Patates douces à chair orangée',
    nameEn: 'Sweet Potatoes (Yams)',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 25,
    pluCode: '4816',
    calories: 86,
    originFr: 'Pastille PLU #4816',
    originEn: 'PLU Sticker #4816',
    brand: 'Sélection Légumes Racine',
    packagingFormatFr: 'Tubercules frais en vrac',
    packagingFormatEn: 'Fresh loose sweet potatoes',
    dietaryBadges: ['Produits frais', 'Code PLU #4816', 'Bêta-carotène'],
    storageTipFr: 'Conserver à température ambiante tempérée dans un endroit sec et sombre.',
    storageTipEn: 'Keep in a cool, dry, dark pantry cupboard.',
    freezerTipFr: 'Rôtir au four, écraser en purée et congeler en portions hermétiques.',
    freezerTipEn: 'Bake, mash, and freeze in sealed bags for pies or side dishes.',
    nutritionSummary: '86 kcal • Excellente source de bêta-carotène et fibres douces',
  },
  'red-beet': {
    id: 'red-beet',
    className: 'Red-Beet',
    nameFr: 'Betteraves rouges fraîches du Québec',
    nameEn: 'Fresh Red Beets',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 28,
    pluCode: '4539',
    calories: 43,
    originFr: 'Maraîchers du Québec • PLU #4539',
    originEn: 'Canada No. 1 Red Beets',
    brand: 'Maraîchers du Québec',
    packagingFormatFr: 'Botte avec fanes ou sac',
    packagingFormatEn: 'Bunch with greens or bagged',
    dietaryBadges: ['Produits frais', 'Code PLU #4539', 'Aliments du Québec'],
    storageTipFr: 'Couper les fanes à 2 cm du collet et conserver les racines au bac à légumes.',
    storageTipEn: 'Trim greens leaving 1 inch of stem and store roots in crisper.',
    freezerTipFr: 'Cuire entières à l’eau ou au four, peler, trancher et congeler.',
    freezerTipEn: 'Boil or roast till tender, slip off skins, slice and freeze.',
    nutritionSummary: '43 kcal • Riches en bétanine et nitrates naturels cardioprotecteurs',
  },
  'beef-tomato': {
    id: 'beef-tomato',
    className: 'Beef-Tomato',
    nameFr: 'Grosses tomates beefsteak charnues',
    nameEn: 'Large Beefsteak Tomatoes',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 6,
    pluCode: '4801',
    calories: 18,
    originFr: 'Serres du Québec No. 1 • PLU #4801',
    originEn: 'Canada No. 1 Beefsteak Tomatoes',
    brand: 'Serres du Québec',
    packagingFormatFr: 'Tomates fraîches en vrac',
    packagingFormatEn: 'Fresh loose tomatoes',
    dietaryBadges: ['Produits frais', 'Code PLU #4801', 'Aliments du Québec'],
    storageTipFr: 'Garder sur le comptoir tige vers le bas. Le réfrigérateur détruit leurs arômes.',
    storageTipEn: 'Store on counter stem-side down at room temp. Cold dulls tomato flavor.',
    freezerTipFr: 'Peler, concasser et congeler en sauce tomate pour pâtes.',
    freezerTipEn: 'Score skins, blanch, crush and freeze in jars for homemade pasta sauce.',
    nutritionSummary: '18 kcal • Charnue, juteuse et gorgée de lycopène',
  },
  'regular-tomato': {
    id: 'regular-tomato',
    className: 'Regular-Tomato',
    nameFr: 'Tomates rondes fraîches de serre',
    nameEn: 'Fresh Round Greenhouse Tomatoes',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 6,
    pluCode: '4087',
    calories: 18,
    originFr: 'Serres locales • PLU #4087',
    originEn: 'Canada No. 1 Round Tomatoes',
    brand: 'Serres du Québec',
    packagingFormatFr: 'Tomates en vrac ou barquette',
    packagingFormatEn: 'Fresh loose or packaged tomatoes',
    dietaryBadges: ['Produits frais', 'Code PLU #4087', 'Aliments du Québec'],
    storageTipFr: 'Conserver sur le comptoir à température ambiante.',
    storageTipEn: 'Keep at room temp on counter.',
    freezerTipFr: 'Mixer et congeler en coulis de tomate maison.',
    freezerTipEn: 'Purée and freeze in ice cube trays for soup bases.',
    nutritionSummary: '18 kcal • Polyvalente pour salades et cuissons',
  },
  'vine-tomato': {
    id: 'vine-tomato',
    className: 'Vine-Tomato',
    nameFr: 'Tomates de serre mûries sur vigne',
    nameEn: 'Vine-Ripened Cluster Tomatoes',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Pantry',
    shelfLife: 7,
    pluCode: '4664',
    calories: 18,
    originFr: 'Serres du Québec No. 1 • PLU #4664',
    originEn: 'Canada No. 1 Vine Tomatoes',
    brand: 'Serres du Québec',
    packagingFormatFr: 'Grappe de tomates sur vigne',
    packagingFormatEn: 'Vine cluster pack',
    dietaryBadges: ['Produits frais', 'Code PLU #4664', 'Aliments du Québec'],
    storageTipFr: 'Conserver la grappe sur le comptoir à température ambiante pour un parfum optimal.',
    storageTipEn: 'Leave on the vine on the countertop for peak natural sweetness.',
    freezerTipFr: 'Rôtir au four avec huile d’olive et ail, puis congeler.',
    freezerTipEn: 'Slow roast with olive oil and garlic, then freeze for pasta sauces.',
    nutritionSummary: '18 kcal • Arôme incomparable de tomate de serre',
  },
  zucchini: {
    id: 'zucchini',
    className: 'Zucchini',
    nameFr: 'Courgettes vertes fraîches (Zucchini)',
    nameEn: 'Fresh Green Zucchini Squash',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 7,
    pluCode: '4067',
    calories: 17,
    originFr: 'Maraîchers locaux No. 1 • PLU #4067',
    originEn: 'Canada No. 1 Zucchini (PLU #4067)',
    brand: 'Maraîchers du Québec',
    packagingFormatFr: 'Courgettes fraîches en vrac',
    packagingFormatEn: 'Fresh loose zucchini',
    dietaryBadges: ['Produits frais', 'Code PLU #4067'],
    storageTipFr: 'Conserver non lavé dans le bac à légumes du réfrigérateur.',
    storageTipEn: 'Keep dry and unwashed in refrigerator crisper drawer.',
    freezerTipFr: 'Râper, presser l’excédent d’eau et congeler en portions pour pains aux courgettes.',
    freezerTipEn: 'Grate, squeeze out moisture, and freeze in ziplock portions for zucchini bread.',
    nutritionSummary: '17 kcal • Léger, digeste et riche en lutéine',
  },
  // Beverages & Juices
  'bravo-apple-juice': {
    id: 'bravo-apple-juice',
    className: 'Bravo-Apple-Juice',
    nameFr: 'Jus de pomme pur 100%',
    nameEn: 'Pure 100% Apple Juice',
    category: 'Beverages',
    categoryFr: 'Boissons & Jus',
    location: 'Fridge',
    shelfLife: 14,
    calories: 45,
    originFr: 'Brique de jus pasteurisé',
    originEn: 'Pasteurized carton juice',
    brand: 'Bravo / Sélection Jus',
    packagingFormatFr: 'Brique carton 1L',
    packagingFormatEn: '1L carton',
    dietaryBadges: ['100% pur jus', 'Sans sucre ajouté'],
    storageTipFr: 'Conserver au réfrigérateur après ouverture et consommer dans les 7 à 10 jours.',
    storageTipEn: 'Keep refrigerated after opening and consume within 7 to 10 days.',
    freezerTipFr: 'Congeler en sucettes glacées pour l’été.',
    freezerTipEn: 'Pour into popsicle molds and freeze for fruit pops.',
    nutritionSummary: '45 kcal • Vitamine C',
  },
  'bravo-orange-juice': {
    id: 'bravo-orange-juice',
    className: 'Bravo-Orange-Juice',
    nameFr: 'Jus d’orange pur pressé',
    nameEn: 'Pure Squeezed Orange Juice',
    category: 'Beverages',
    categoryFr: 'Boissons & Jus',
    location: 'Fridge',
    shelfLife: 14,
    calories: 45,
    originFr: 'Brique de jus d’orange',
    originEn: 'Carton orange juice',
    brand: 'Bravo',
    packagingFormatFr: 'Brique carton 1L',
    packagingFormatEn: '1L carton',
    dietaryBadges: ['100% pur jus', 'Vitamine C'],
    storageTipFr: 'Bien agiter avant de servir. Conserver au réfrigérateur.',
    storageTipEn: 'Shake well before serving. Keep chilled.',
    freezerTipFr: 'Congeler dans un bac à glaçons pour smoothies matinaux.',
    freezerTipEn: 'Freeze in cube trays for morning breakfast smoothies.',
    nutritionSummary: '45 kcal • Source de vitamine C',
  },
  'god-morgon-apple-juice': {
    id: 'god-morgon-apple-juice',
    className: 'God-Morgon-Apple-Juice',
    nameFr: 'Jus de pomme doux de dégustation',
    nameEn: 'Premium Apple Juice',
    category: 'Beverages',
    categoryFr: 'Boissons & Jus',
    location: 'Fridge',
    shelfLife: 14,
    calories: 46,
    originFr: 'Jus réfrigéré premium',
    originEn: 'Premium chilled juice',
    brand: 'God Morgon',
    packagingFormatFr: 'Brique carton réfrigérée',
    packagingFormatEn: 'Chilled carton',
    dietaryBadges: ['100% pur jus'],
    storageTipFr: 'Conserver au réfrigérateur en tout temps.',
    storageTipEn: 'Keep refrigerated at all times.',
    freezerTipFr: 'Congeler en portions pour sorbet express.',
    freezerTipEn: 'Freeze for granitas or sorbets.',
    nutritionSummary: '46 kcal • Pur jus',
  },
  'god-morgon-orange-juice': {
    id: 'god-morgon-orange-juice',
    className: 'God-Morgon-Orange-Juice',
    nameFr: 'Jus d’orange doux avec pulpe',
    nameEn: 'Orange Juice with Pulp',
    category: 'Beverages',
    categoryFr: 'Boissons & Jus',
    location: 'Fridge',
    shelfLife: 14,
    calories: 45,
    originFr: 'Jus réfrigéré pur',
    originEn: 'Chilled pure juice',
    brand: 'God Morgon',
    packagingFormatFr: 'Brique carton 1L',
    packagingFormatEn: '1L carton',
    dietaryBadges: ['100% pur jus', 'Vitamine C'],
    storageTipFr: 'Conserver au frais.',
    storageTipEn: 'Store in refrigerator.',
    freezerTipFr: 'Congeler en glaçons pour rafraîchir cocktails d’été.',
    freezerTipEn: 'Freeze in ice cubes for summer punch.',
    nutritionSummary: '45 kcal • Riche en pulpe',
  },
  'god-morgon-orange-red-grapefruit-juice': {
    id: 'god-morgon-orange-red-grapefruit-juice',
    className: 'God-Morgon-Orange-Red-Grapefruit-Juice',
    nameFr: 'Jus Orange & Pamplemousse rose',
    nameEn: 'Orange & Pink Grapefruit Juice',
    category: 'Beverages',
    categoryFr: 'Boissons & Jus',
    location: 'Fridge',
    shelfLife: 14,
    calories: 42,
    originFr: 'Pur jus d’agrumes',
    originEn: 'Pure citrus blend',
    brand: 'God Morgon',
    packagingFormatFr: 'Brique carton',
    packagingFormatEn: 'Carton pack',
    dietaryBadges: ['100% pur jus'],
    storageTipFr: 'Conserver au frais au réfrigérateur.',
    storageTipEn: 'Keep refrigerated.',
    freezerTipFr: 'Congeler en sucettes glacées.',
    freezerTipEn: 'Freeze into popsicle molds.',
    nutritionSummary: '42 kcal • Agrumes vifs',
  },
  'god-morgon-red-grapefruit-juice': {
    id: 'god-morgon-red-grapefruit-juice',
    className: 'God-Morgon-Red-Grapefruit-Juice',
    nameFr: 'Jus de pamplemousse rose 100%',
    nameEn: '100% Pink Grapefruit Juice',
    category: 'Beverages',
    categoryFr: 'Boissons & Jus',
    location: 'Fridge',
    shelfLife: 14,
    calories: 40,
    originFr: 'Pur jus de pamplemousse',
    originEn: 'Pure grapefruit juice',
    brand: 'God Morgon',
    packagingFormatFr: 'Brique carton',
    packagingFormatEn: 'Carton',
    dietaryBadges: ['100% pur jus'],
    storageTipFr: 'Garder au réfrigérateur.',
    storageTipEn: 'Store refrigerated.',
    freezerTipFr: 'Congeler pour granités rafraîchissants.',
    freezerTipEn: 'Freeze for refreshing granitas.',
    nutritionSummary: '40 kcal • Tonique naturel',
  },
  'tropicana-apple-juice': {
    id: 'tropicana-apple-juice',
    className: 'Tropicana-Apple-Juice',
    nameFr: 'Jus de pomme Tropicana 100% pur',
    nameEn: 'Tropicana 100% Pure Apple Juice',
    category: 'Beverages',
    categoryFr: 'Boissons & Jus',
    location: 'Fridge',
    shelfLife: 16,
    calories: 48,
    originFr: 'Bouteille réfrigérée pur jus',
    originEn: 'Pure chilled juice',
    brand: 'Tropicana',
    packagingFormatFr: 'Bouteille ou brique réfrigérée',
    packagingFormatEn: 'Chilled bottle / carton',
    dietaryBadges: ['100% pur jus', 'Sans sucre ajouté'],
    storageTipFr: 'Conserver au réfrigérateur entre 1°C et 4°C.',
    storageTipEn: 'Store refrigerated between 1°C and 4°C.',
    freezerTipFr: 'Congeler en bâtonnets glacés.',
    freezerTipEn: 'Freeze in ice pop molds.',
    nutritionSummary: '48 kcal • Pur jus pressé',
  },
  'tropicana-golden-grapefruit': {
    id: 'tropicana-golden-grapefruit',
    className: 'Tropicana-Golden-Grapefruit',
    nameFr: 'Jus de pamplemousse doré Tropicana',
    nameEn: 'Tropicana Golden Grapefruit Juice',
    category: 'Beverages',
    categoryFr: 'Boissons & Jus',
    location: 'Fridge',
    shelfLife: 14,
    calories: 42,
    originFr: 'Pur jus d’agrumes pressé',
    originEn: 'Pure citrus juice',
    brand: 'Tropicana',
    packagingFormatFr: 'Bouteille réfrigérée',
    packagingFormatEn: 'Chilled bottle',
    dietaryBadges: ['100% pur jus'],
    storageTipFr: 'Conserver au réfrigérateur.',
    storageTipEn: 'Keep refrigerated.',
    freezerTipFr: 'Congeler en glaçons.',
    freezerTipEn: 'Freeze in ice cube trays.',
    nutritionSummary: '42 kcal • Agrumes dorés',
  },
  'tropicana-juice-smooth': {
    id: 'tropicana-juice-smooth',
    className: 'Tropicana-Juice-Smooth',
    nameFr: 'Jus d’orange Tropicana sans pulpe (Pur Premium)',
    nameEn: 'Tropicana Pure Premium Smooth No Pulp Orange Juice',
    category: 'Beverages',
    categoryFr: 'Boissons & Jus',
    location: 'Fridge',
    shelfLife: 16,
    calories: 45,
    originFr: 'Pur jus d’orange pressé sans pulpe',
    originEn: 'Pure premium orange juice',
    brand: 'Tropicana',
    packagingFormatFr: 'Bouteille carton réfrigérée',
    packagingFormatEn: 'Carton bottle',
    dietaryBadges: ['100% pur jus', 'Vitamine C'],
    storageTipFr: 'Garder toujours au réfrigérateur.',
    storageTipEn: 'Always keep refrigerated.',
    freezerTipFr: 'Congeler pour smoothies.',
    freezerTipEn: 'Freeze in portions for smoothies.',
    nutritionSummary: '45 kcal • 100% jus pressé sans pulpe',
  },
  'tropicana-mandarin-morning': {
    id: 'tropicana-mandarin-morning',
    className: 'Tropicana-Mandarin-Morning',
    nameFr: 'Jus Orange & Mandarine Tropicana Réveil Doux',
    nameEn: 'Tropicana Mandarin Morning Juice',
    category: 'Beverages',
    categoryFr: 'Boissons & Jus',
    location: 'Fridge',
    shelfLife: 14,
    calories: 46,
    originFr: 'Mélange agrumes doux',
    originEn: 'Sweet citrus blend',
    brand: 'Tropicana',
    packagingFormatFr: 'Bouteille réfrigérée',
    packagingFormatEn: 'Chilled bottle',
    dietaryBadges: ['100% pur jus'],
    storageTipFr: 'Conserver au frais.',
    storageTipEn: 'Store chilled.',
    freezerTipFr: 'Congeler en portions.',
    freezerTipEn: 'Freeze for slushies.',
    nutritionSummary: '46 kcal • Douceur mandarine',
  },
  // Dairy & Plant-based Milks
  'arla-ecological-medium-fat-milk': {
    id: 'arla-ecological-medium-fat-milk',
    className: 'Arla-Ecological-Medium-Fat-Milk',
    nameFr: 'Lait biologique 2% partiellement écrémé',
    nameEn: 'Organic 2% Partly Skimmed Milk',
    category: 'Dairy',
    categoryFr: 'Produits laitiers',
    location: 'Fridge',
    shelfLife: 10,
    calories: 50,
    originFr: 'Lait biologique pasteurisé',
    originEn: 'Pasteurized organic milk',
    brand: 'Arla / Sélection Bio',
    packagingFormatFr: 'Carton de lait 1L ou 2L',
    packagingFormatEn: '1L or 2L milk carton',
    dietaryBadges: ['Biologique', 'Calcium', 'Vitamine D'],
    storageTipFr: 'Conserver entre 1°C et 4°C sur les étagères intérieures du réfrigérateur.',
    storageTipEn: 'Store between 1°C and 4°C on middle fridge shelves, not the door.',
    freezerTipFr: 'Peut être congelé avant la date de péremption ; bien décongeler au réfrigérateur.',
    freezerTipEn: 'Can be frozen before expiry date; shake well after thawing in fridge.',
    nutritionSummary: '50 kcal • Riche en calcium et protéines laitières',
  },
  'arla-lactose-medium-fat-milk': {
    id: 'arla-lactose-medium-fat-milk',
    className: 'Arla-Lactose-Medium-Fat-Milk',
    nameFr: 'Lait 2% sans lactose',
    nameEn: 'Lactose-Free 2% Milk',
    category: 'Dairy',
    categoryFr: 'Produits laitiers',
    location: 'Fridge',
    shelfLife: 14,
    calories: 50,
    originFr: 'Lait frais filtré sans lactose',
    originEn: 'Lactose-free fresh milk',
    brand: 'Sélection Sans Lactose',
    packagingFormatFr: 'Carton de lait',
    packagingFormatEn: 'Milk carton',
    dietaryBadges: ['Sans lactose', 'Calcium'],
    storageTipFr: 'Garder bien au frais.',
    storageTipEn: 'Keep chilled in fridge.',
    freezerTipFr: 'Congeler en portions pour cuisine.',
    freezerTipEn: 'Freeze in cups for cooking.',
    nutritionSummary: '50 kcal • Digestion facile sans lactose',
  },
  'arla-medium-fat-milk': {
    id: 'arla-medium-fat-milk',
    className: 'Arla-Medium-Fat-Milk',
    nameFr: 'Lait 2% partiellement écrémé',
    nameEn: 'Partly Skimmed 2% Milk',
    category: 'Dairy',
    categoryFr: 'Produits laitiers',
    location: 'Fridge',
    shelfLife: 10,
    calories: 50,
    originFr: 'Lait frais pasteurisé',
    originEn: 'Fresh pasteurized milk',
    brand: 'Laiterie Fraîche',
    packagingFormatFr: 'Carton ou pinte de lait',
    packagingFormatEn: 'Milk carton',
    dietaryBadges: ['Produits laitiers', 'Calcium'],
    storageTipFr: 'Conserver au réfrigérateur.',
    storageTipEn: 'Keep refrigerated.',
    freezerTipFr: 'Congeler dans un récipient laissant de l’espace pour expansion.',
    freezerTipEn: 'Freeze leaving headspace in container.',
    nutritionSummary: '50 kcal • Calcium & Vitamine D',
  },
  'arla-standard-milk': {
    id: 'arla-standard-milk',
    className: 'Arla-Standard-Milk',
    nameFr: 'Lait entier 3.25% (Lait homogénéisé)',
    nameEn: 'Whole Milk 3.25% (Homogenized)',
    category: 'Dairy',
    categoryFr: 'Produits laitiers',
    location: 'Fridge',
    shelfLife: 10,
    calories: 62,
    originFr: 'Lait entier de ferme',
    originEn: 'Whole farm fresh milk',
    brand: 'Laiterie Locale',
    packagingFormatFr: 'Carton de lait entier',
    packagingFormatEn: 'Whole milk carton',
    dietaryBadges: ['Lait entier', 'Calcium'],
    storageTipFr: 'Conserver bien froid au réfrigérateur.',
    storageTipEn: 'Store cold in fridge.',
    freezerTipFr: 'Congeler pour préparations culinaires et béchamels.',
    freezerTipEn: 'Freeze for white sauces and baking.',
    nutritionSummary: '62 kcal • Onctueux et riche',
  },
  'garant-ecological-medium-fat-milk': {
    id: 'garant-ecological-medium-fat-milk',
    className: 'Garant-Ecological-Medium-Fat-Milk',
    nameFr: 'Lait bio 2% québécois / local',
    nameEn: 'Organic 2% Local Milk',
    category: 'Dairy',
    categoryFr: 'Produits laitiers',
    location: 'Fridge',
    shelfLife: 10,
    calories: 50,
    originFr: 'Lait bio certifié',
    originEn: 'Certified organic milk',
    brand: 'Garant Bio',
    packagingFormatFr: 'Brique carton',
    packagingFormatEn: 'Carton',
    dietaryBadges: ['Biologique', 'Calcium'],
    storageTipFr: 'Conserver au réfrigérateur.',
    storageTipEn: 'Keep refrigerated.',
    freezerTipFr: 'Congeler pour pâtisserie.',
    freezerTipEn: 'Freeze for baking.',
    nutritionSummary: '50 kcal • Bio certifié',
  },
  'garant-ecological-standard-milk': {
    id: 'garant-ecological-standard-milk',
    className: 'Garant-Ecological-Standard-Milk',
    nameFr: 'Lait entier bio 3.25%',
    nameEn: 'Organic Whole Milk 3.25%',
    category: 'Dairy',
    categoryFr: 'Produits laitiers',
    location: 'Fridge',
    shelfLife: 10,
    calories: 62,
    originFr: 'Lait entier biologique',
    originEn: 'Organic whole milk',
    brand: 'Garant Bio',
    packagingFormatFr: 'Carton',
    packagingFormatEn: 'Carton',
    dietaryBadges: ['Biologique'],
    storageTipFr: 'Garder bien au frais.',
    storageTipEn: 'Keep cold in fridge.',
    freezerTipFr: 'Congeler pour sauces et crèmes.',
    freezerTipEn: 'Freeze for sauces.',
    nutritionSummary: '62 kcal • Lait bio entier',
  },
  'oatly-natural-oatghurt': {
    id: 'oatly-natural-oatghurt',
    className: 'Oatly-Natural-Oatghurt',
    nameFr: 'Yogourt végétal à l’avoine nature',
    nameEn: 'Plant-Based Plain Oat Yogurt',
    category: 'Dairy',
    categoryFr: 'Produits laitiers & végétaux',
    location: 'Fridge',
    shelfLife: 14,
    calories: 70,
    originFr: 'Alternative végétale à base d’avoine',
    originEn: 'Plant-based oat cultured yogurt',
    brand: 'Oatly',
    packagingFormatFr: 'Pot de yogourt 500g',
    packagingFormatEn: '500g yogurt tub',
    dietaryBadges: ['Végétalien', 'Sans lactose', 'À base d’avoine'],
    storageTipFr: 'Conserver au réfrigérateur et consommer dans les 5 jours après ouverture.',
    storageTipEn: 'Store refrigerated and consume within 5 days of opening.',
    freezerTipFr: 'Congeler en cubes pour smoothies onctueux sans produits laitiers.',
    freezerTipEn: 'Freeze in cube trays for dairy-free smoothie bases.',
    nutritionSummary: '70 kcal • 100% végétal et doux pour l’estomac',
  },
  'oatly-oat-milk': {
    id: 'oatly-oat-milk',
    className: 'Oatly-Oat-Milk',
    nameFr: 'Boisson d’avoine originale (Lait d’avoine)',
    nameEn: 'Original Oat Milk (Barista / Classic)',
    category: 'Dairy',
    categoryFr: 'Produits laitiers & végétaux',
    location: 'Fridge',
    shelfLife: 14,
    calories: 47,
    originFr: 'Boisson végétale d’avoine enrichie',
    originEn: 'Fortified oat beverage',
    brand: 'Oatly',
    packagingFormatFr: 'Brique carton 946ml / 1L',
    packagingFormatEn: '1L carton',
    dietaryBadges: ['Végétalien', 'Sans lactose', 'Sans soja'],
    storageTipFr: 'Bien secouer avant emploi. Réfrigérer après ouverture.',
    storageTipEn: 'Shake well before using. Keep refrigerated once opened.',
    freezerTipFr: 'Non recommandé pour la congélation car la texture peut se déphaser.',
    freezerTipEn: 'Freezing may cause separation; stir well if used in baking.',
    nutritionSummary: '47 kcal • Enrichi en calcium et vitamine D',
  },
  'arla-ecological-sour-cream': {
    id: 'arla-ecological-sour-cream',
    className: 'Arla-Ecological-Sour-Cream',
    nameFr: 'Crème sure biologique 14%',
    nameEn: 'Organic 14% Sour Cream',
    category: 'Dairy',
    categoryFr: 'Produits laitiers',
    location: 'Fridge',
    shelfLife: 21,
    calories: 140,
    originFr: 'Crème sure bio fraîche',
    originEn: 'Organic cultured sour cream',
    brand: 'Arla Bio',
    packagingFormatFr: 'Pot de 250ml / 500ml',
    packagingFormatEn: 'Sour cream tub',
    dietaryBadges: ['Biologique', 'Produits laitiers'],
    storageTipFr: 'Conserver au réfrigérateur. Ne pas laisser à température ambiante.',
    storageTipEn: 'Keep refrigerated. Do not leave at room temperature.',
    freezerTipFr: 'La congélation altère la texture de la crème sure ; utiliser cuisinée.',
    freezerTipEn: 'Freezing may separate cream; best used in cooked casseroles.',
    nutritionSummary: '140 kcal • Onctueuse et acidulée',
  },
  'arla-sour-cream': {
    id: 'arla-sour-cream',
    className: 'Arla-Sour-Cream',
    nameFr: 'Crème sure classique 14%',
    nameEn: 'Traditional 14% Sour Cream',
    category: 'Dairy',
    categoryFr: 'Produits laitiers',
    location: 'Fridge',
    shelfLife: 21,
    calories: 140,
    originFr: 'Crème sure fraîche pasteurisée',
    originEn: 'Fresh cultured sour cream',
    brand: 'Laiterie Locale',
    packagingFormatFr: 'Pot de crème sure',
    packagingFormatEn: 'Plastic tub',
    dietaryBadges: ['Produits laitiers'],
    storageTipFr: 'Conserver au réfrigérateur.',
    storageTipEn: 'Store in fridge.',
    freezerTipFr: 'Utiliser en pâtisserie après décongélation.',
    freezerTipEn: 'Use in baked goods once thawed.',
    nutritionSummary: '140 kcal • Texture crémeuse',
  },
  'arla-sour-milk': {
    id: 'arla-sour-milk',
    className: 'Arla-Sour-Milk',
    nameFr: 'Babeurre / Lait ribot traditionnel',
    nameEn: 'Traditional Buttermilk / Cultured Milk',
    category: 'Dairy',
    categoryFr: 'Produits laitiers',
    location: 'Fridge',
    shelfLife: 14,
    calories: 45,
    originFr: 'Lait de culture traditionnel',
    originEn: 'Cultured buttermilk',
    brand: 'Laiterie Locale',
    packagingFormatFr: 'Carton 1L',
    packagingFormatEn: '1L carton',
    dietaryBadges: ['Ferments lactiques'],
    storageTipFr: 'Conserver au réfrigérateur.',
    storageTipEn: 'Keep refrigerated.',
    freezerTipFr: 'Congeler en portions pour crêpes et gâteaux moelleux.',
    freezerTipEn: 'Freeze in portions for pancakes and biscuits.',
    nutritionSummary: '45 kcal • Idéal pour attendrir les viandes et pâtisseries',
  },
  'alpro-blueberry-soyghurt': {
    id: 'alpro-blueberry-soyghurt',
    className: 'Alpro-Blueberry-Soyghurt',
    nameFr: 'Yogourt de soya aux bleuets',
    nameEn: 'Blueberry Soy Cultured Yogurt',
    category: 'Dairy',
    categoryFr: 'Produits laitiers & végétaux',
    location: 'Fridge',
    shelfLife: 14,
    calories: 75,
    originFr: 'Alternative végétale au soya',
    originEn: 'Cultured plant-based soy yogurt',
    brand: 'Alpro',
    packagingFormatFr: 'Pot de 500g ou 4x100g',
    packagingFormatEn: 'Tub or multi-pack',
    dietaryBadges: ['Végétalien', 'Sans lactose', 'Protéines végétales'],
    storageTipFr: 'Conserver au réfrigérateur.',
    storageTipEn: 'Keep chilled in fridge.',
    freezerTipFr: 'Congeler en petits pots pour glaces saines aux bleuets.',
    freezerTipEn: 'Freeze in small tubs for healthy blueberry frozen treats.',
    nutritionSummary: '75 kcal • Riche en bleuets et protéines végétales',
  },
  'alpro-vanilla-soyghurt': {
    id: 'alpro-vanilla-soyghurt',
    className: 'Alpro-Vanilla-Soyghurt',
    nameFr: 'Yogourt de soya à la vanille',
    nameEn: 'Vanilla Soy Cultured Yogurt',
    category: 'Dairy',
    categoryFr: 'Produits laitiers & végétaux',
    location: 'Fridge',
    shelfLife: 14,
    calories: 78,
    originFr: 'Yogourt végétal vanille',
    originEn: 'Vanilla soy yogurt',
    brand: 'Alpro',
    packagingFormatFr: 'Pot de 500g',
    packagingFormatEn: '500g tub',
    dietaryBadges: ['Végétalien', 'Sans lactose'],
    storageTipFr: 'Conserver au réfrigérateur.',
    storageTipEn: 'Keep refrigerated.',
    freezerTipFr: 'Congeler avec des baies pour dessert glacé.',
    freezerTipEn: 'Freeze with berries for frozen yogurt.',
    nutritionSummary: '78 kcal • Vanille naturelle',
  },
  'alpro-fresh-soy-milk': {
    id: 'alpro-fresh-soy-milk',
    className: 'Alpro-Fresh-Soy-Milk',
    nameFr: 'Boisson de soya fraîche originale (Lait de soya)',
    nameEn: 'Fresh Soy Milk Original',
    category: 'Dairy',
    categoryFr: 'Produits laitiers & végétaux',
    location: 'Fridge',
    shelfLife: 12,
    calories: 42,
    originFr: 'Boisson de soya enrichie',
    originEn: 'Enriched soy beverage',
    brand: 'Alpro',
    packagingFormatFr: 'Brique carton 1L',
    packagingFormatEn: '1L carton',
    dietaryBadges: ['Végétalien', 'Sans lactose', 'Source de protéines'],
    storageTipFr: 'Bien agiter avant chaque utilisation. Réfrigérer.',
    storageTipEn: 'Shake well before pouring. Keep cold.',
    freezerTipFr: 'Congeler en portions pour soupes ou sauces.',
    freezerTipEn: 'Freeze in recipe-sized portions for cooking.',
    nutritionSummary: '42 kcal • Riche en protéines végétales de haute qualité',
  },
  'alpro-shelf-soy-milk': {
    id: 'alpro-shelf-soy-milk',
    className: 'Alpro-Shelf-Soy-Milk',
    nameFr: 'Boisson de soya de longue conservation',
    nameEn: 'Shelf-Stable Soy Milk',
    category: 'Dairy',
    categoryFr: 'Produits laitiers & végétaux',
    location: 'Pantry',
    shelfLife: 90,
    calories: 42,
    originFr: 'Boisson de soya UHT',
    originEn: 'UHT shelf-stable soy beverage',
    brand: 'Alpro',
    packagingFormatFr: 'Tétra brique 1L',
    packagingFormatEn: '1L tetra pack',
    dietaryBadges: ['Végétalien', 'Sans lactose', 'Longue conservation'],
    storageTipFr: 'Garder au garde-manger jusqu’à ouverture, puis réfrigérer.',
    storageTipEn: 'Store in pantry until opened, then refrigerate.',
    freezerTipFr: 'Congeler pour utilisation en cuisine.',
    freezerTipEn: 'Freeze in measuring cups for recipes.',
    nutritionSummary: '42 kcal • Pratique en réserve d’épicerie',
  },
  'arla-mild-vanilla-yoghurt': {
    id: 'arla-mild-vanilla-yoghurt',
    className: 'Arla-Mild-Vanilla-Yoghurt',
    nameFr: 'Yogourt doux vanillé velouté',
    nameEn: 'Smooth Mild Vanilla Yogurt',
    category: 'Dairy',
    categoryFr: 'Produits laitiers',
    location: 'Fridge',
    shelfLife: 14,
    calories: 82,
    originFr: 'Lait pasteurisé et vanille',
    originEn: 'Cultured vanilla yogurt',
    brand: 'Laiterie Locale',
    packagingFormatFr: 'Pot de 750g / 1 kg',
    packagingFormatEn: '750g / 1 kg yogurt tub',
    dietaryBadges: ['Produits laitiers', 'Probiotiques'],
    storageTipFr: 'Conserver au réfrigérateur bien fermé.',
    storageTipEn: 'Keep securely sealed in fridge.',
    freezerTipFr: 'Étaler sur une plaque avec des pépites de chocolat et congeler pour bark glacé au yogourt.',
    freezerTipEn: 'Spread on parchment with fruit and freeze for healthy yogurt bark.',
    nutritionSummary: '82 kcal • Doux et vanillé',
  },
  'arla-natural-mild-low-fat-yoghurt': {
    id: 'arla-natural-mild-low-fat-yoghurt',
    className: 'Arla-Natural-Mild-Low-Fat-Yoghurt',
    nameFr: 'Yogourt nature doux faible en gras (1%)',
    nameEn: 'Mild Low-Fat Plain Yogurt (1%)',
    category: 'Dairy',
    categoryFr: 'Produits laitiers',
    location: 'Fridge',
    shelfLife: 14,
    calories: 48,
    originFr: 'Lait partiellement écrémé de culture',
    originEn: 'Cultured low-fat yogurt',
    brand: 'Laiterie Fraîche',
    packagingFormatFr: 'Pot de 750g',
    packagingFormatEn: '750g tub',
    dietaryBadges: ['Faible en gras', 'Probiotiques'],
    storageTipFr: 'Conserver au réfrigérateur.',
    storageTipEn: 'Keep cold in fridge.',
    freezerTipFr: 'Congeler pour smoothies protéinés.',
    freezerTipEn: 'Freeze in ice cubes for protein shakes.',
    nutritionSummary: '48 kcal • Léger et source de calcium',
  },
  'arla-natural-yoghurt': {
    id: 'arla-natural-yoghurt',
    className: 'Arla-Natural-Yoghurt',
    nameFr: 'Yogourt nature classique crémeux',
    nameEn: 'Classic Plain Creamy Yogurt',
    category: 'Dairy',
    categoryFr: 'Produits laitiers',
    location: 'Fridge',
    shelfLife: 14,
    calories: 60,
    originFr: 'Lait entier pasteurisé de culture',
    originEn: 'Whole milk cultured yogurt',
    brand: 'Laiterie Locale',
    packagingFormatFr: 'Pot de 750g',
    packagingFormatEn: '750g tub',
    dietaryBadges: ['Produits laitiers', 'Sans sucre ajouté'],
    storageTipFr: 'Conserver au réfrigérateur.',
    storageTipEn: 'Store refrigerated.',
    freezerTipFr: 'Égoutter dans une étamine pour obtenir du labneh crémeux.',
    freezerTipEn: 'Strain through cheesecloth for thick homemade labneh.',
    nutritionSummary: '60 kcal • Pur et sans sucre ajouté',
  },
  'valio-vanilla-yoghurt': {
    id: 'valio-vanilla-yoghurt',
    className: 'Valio-Vanilla-Yoghurt',
    nameFr: 'Yogourt vanille boréal onctueux',
    nameEn: 'Creamy Vanilla Yogurt',
    category: 'Dairy',
    categoryFr: 'Produits laitiers',
    location: 'Fridge',
    shelfLife: 14,
    calories: 85,
    originFr: 'Yogourt fermenté à la vanille',
    originEn: 'Cultured vanilla yogurt',
    brand: 'Valio',
    packagingFormatFr: 'Pot carton',
    packagingFormatEn: 'Carton tub',
    dietaryBadges: ['Produits laitiers', 'Probiotiques'],
    storageTipFr: 'Conserver au réfrigérateur.',
    storageTipEn: 'Store in fridge.',
    freezerTipFr: 'Congeler en esquimaux.',
    freezerTipEn: 'Freeze as frozen yogurt pops.',
    nutritionSummary: '85 kcal • Vanille onctueuse',
  },
  'yoggi-strawberry-yoghurt': {
    id: 'yoggi-strawberry-yoghurt',
    className: 'Yoggi-Strawberry-Yoghurt',
    nameFr: 'Yogourt brassé aux fraises savoureuses',
    nameEn: 'Stirred Strawberry Fruit Yogurt',
    category: 'Dairy',
    categoryFr: 'Produits laitiers',
    location: 'Fridge',
    shelfLife: 14,
    calories: 84,
    originFr: 'Yogourt brassé avec vrais morceaux de fraises',
    originEn: 'Cultured fruit yogurt with real strawberries',
    brand: 'Yoggi',
    packagingFormatFr: 'Pot de 500g ou 1 kg',
    packagingFormatEn: '500g or 1 kg tub',
    dietaryBadges: ['Morceaux de fruits', 'Probiotiques'],
    storageTipFr: 'Conserver au frais au réfrigérateur.',
    storageTipEn: 'Keep refrigerated.',
    freezerTipFr: 'Congeler pour desserts glacés fruités.',
    freezerTipEn: 'Freeze into fruit yogurt pops.',
    nutritionSummary: '84 kcal • Vraies fraises et ferments actifs',
  },
  'yoggi-vanilla-yoghurt': {
    id: 'yoggi-vanilla-yoghurt',
    className: 'Yoggi-Vanilla-Yoghurt',
    nameFr: 'Yogourt brassé à la vanille de Madagascar',
    nameEn: 'Madagascar Vanilla Stirred Yogurt',
    category: 'Dairy',
    categoryFr: 'Produits laitiers',
    location: 'Fridge',
    shelfLife: 14,
    calories: 85,
    originFr: 'Yogourt brassé parfumé',
    originEn: 'Cultured vanilla yogurt',
    brand: 'Yoggi',
    packagingFormatFr: 'Pot de 1 kg',
    packagingFormatEn: '1 kg tub',
    dietaryBadges: ['Produits laitiers'],
    storageTipFr: 'Conserver au réfrigérateur.',
    storageTipEn: 'Store refrigerated.',
    freezerTipFr: 'Congeler pour glaces au yogourt maison.',
    freezerTipEn: 'Freeze for homemade frozen yogurt.',
    nutritionSummary: '85 kcal • Goût vanillé crémeux',
  },
  strawberry: {
    id: 'strawberry',
    className: 'Strawberry',
    nameFr: 'Fraises fraîches sucrées du Québec',
    nameEn: 'Fresh Sweet Strawberries',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 4,
    pluCode: '4249',
    calories: 32,
    originFr: 'Île d’Orléans / Québec • Pastille PLU #4249',
    originEn: 'Canadian Berries • PLU Sticker #4249',
    brand: 'Fraises de saison',
    packagingFormatFr: 'Panier ou casseau ajouré (1L / 1 pint)',
    packagingFormatEn: 'Fresh clamshell / basket',
    dietaryBadges: ['Produits frais', 'Code PLU #4249', 'Vitamine C', 'Aliments du Québec'],
    storageTipFr: 'Conserver au frigo non lavées avec un papier absorbant dans le contenant ajouré.',
    storageTipEn: 'Store unwashed with paper towel in original vented clamshell.',
    freezerTipFr: 'Équeuter et congeler entières sur une plaque avant de mettre en sac hermétique.',
    freezerTipEn: 'Hull stems and freeze whole on a sheet pan before bagging.',
    nutritionSummary: '32 kcal • Riche en Vitamine C et antioxydants',
  },
  strawberries: {
    id: 'strawberries',
    className: 'Strawberry',
    nameFr: 'Fraises fraîches sucrées du Québec',
    nameEn: 'Fresh Sweet Strawberries',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 4,
    pluCode: '4249',
    calories: 32,
    originFr: 'Île d’Orléans / Québec • Pastille PLU #4249',
    originEn: 'Canadian Berries • PLU Sticker #4249',
    brand: 'Fraises de saison',
    packagingFormatFr: 'Panier ou casseau ajouré (1L / 1 pint)',
    packagingFormatEn: 'Fresh clamshell / basket',
    dietaryBadges: ['Produits frais', 'Code PLU #4249', 'Vitamine C', 'Aliments du Québec'],
    storageTipFr: 'Conserver au frigo non lavées avec un papier absorbant dans le contenant ajouré.',
    storageTipEn: 'Store unwashed with paper towel in original vented clamshell.',
    freezerTipFr: 'Équeuter et congeler entières sur une plaque avant de mettre en sac hermétique.',
    freezerTipEn: 'Hull stems and freeze whole on a sheet pan before bagging.',
    nutritionSummary: '32 kcal • Riche en Vitamine C et antioxydants',
  },
  blueberry: {
    id: 'blueberry',
    className: 'Blueberry',
    nameFr: 'Bleuets frais du Lac-Saint-Jean',
    nameEn: 'Fresh Wild Blueberries',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 8,
    pluCode: '4240',
    calories: 57,
    originFr: 'Bleuets du Lac-Saint-Jean, Québec • PLU #4240',
    originEn: 'Product of Quebec / Canada • PLU #4240',
    brand: 'Bleuets sauvages',
    packagingFormatFr: 'Panier / barquette de bleuets frais',
    packagingFormatEn: 'Fresh blueberry clamshell',
    dietaryBadges: ['Produits frais', 'Code PLU #4240', 'Aliments du Québec', 'Antioxydants'],
    storageTipFr: 'Conserver au frigo sans laver avant consommation.',
    storageTipEn: 'Keep refrigerated and dry until ready to eat.',
    freezerTipFr: 'Congeler directement tels quels sans laver pour qu’ils restent intacts.',
    freezerTipEn: 'Freeze directly on tray unwashed, pack in bags.',
    nutritionSummary: '57 kcal • Super-aliment antioxydant',
  },
  raspberry: {
    id: 'raspberry',
    className: 'Raspberry',
    nameFr: 'Framboises fraîches tendres',
    nameEn: 'Fresh Tender Raspberries',
    category: 'Produce',
    categoryFr: 'Produits frais',
    location: 'Fridge',
    shelfLife: 3,
    pluCode: '4252',
    calories: 52,
    originFr: 'Québec / Canada • Pastille PLU #4252',
    originEn: 'Product of Canada • PLU #4252',
    brand: 'Petits fruits frais',
    packagingFormatFr: 'Barquette ajourée de framboises',
    packagingFormatEn: 'Vented raspberry clamshell',
    dietaryBadges: ['Produits frais', 'Code PLU #4252', 'Fibres'],
    storageTipFr: 'Très délicates : garder au froid sur papier absorbant, consommer rapidement.',
    storageTipEn: 'Very delicate: store cold on paper towel, eat quickly.',
    freezerTipFr: 'Congeler à plat sur une plaque sans contact, puis ensacher.',
    freezerTipEn: 'Flash freeze flat on sheet pan without touching, then bag.',
    nutritionSummary: '52 kcal • Exceptionnellement riche en fibres',
  },
};

/**
 * Normalizes class name (e.g. 'Golden-Delicious' -> 'golden-delicious')
 */
export function normalizeClassKey(raw: string): string {
  return (raw || '').toLowerCase().replace(/[_\s]+/g, '-').trim();
}

/**
 * Finds catalog item for a given predicted class or label
 */
export function findCatalogItemByClass(rawClass: string): GroceryCatalogItem | null {
  const norm = normalizeClassKey(rawClass);
  if (GROCERY_CATALOG[norm]) return GROCERY_CATALOG[norm];

  // Fallback search by partial word match
  for (const [key, item] of Object.entries(GROCERY_CATALOG)) {
    if (norm.includes(key) || key.includes(norm)) return item;
    if (item.nameEn.toLowerCase().includes(norm) || item.nameFr.toLowerCase().includes(norm)) return item;
  }
  return null;
}
