/**
 * Canadian Food & Open Grocery Intelligence Service
 * 
 * Integrates open-source food databases with a primary concentration on Canada:
 * 1. Canadian Nutrient File (CNF) / Fichier canadien sur les éléments nutritifs (Health Canada)
 * 2. IFPS Global PLU Produce Database (Canadian retail standard for fresh produce)
 * 3. Open Food Facts Canada & Global (ca.openfoodfacts.org / world.openfoodfacts.org)
 * 4. USDA FoodData Central reference & Quebec Grocery Brand Catalog
 */

import fetch from "node-fetch";
import { translateFoodItem, getBilingualNames } from "./foodTranslator.js";

// ============================================================================
// 1. IFPS GLOBAL PRODUCE PLU DATABASE (Canadian Grocery Retail Standard)
// ============================================================================
export const IFPS_PLU_CODES = {
  // --- BERRIES & POMEGRANATES ---
  "4249": {
    nameFr: "Fraises fraîches sucrées du Québec",
    nameEn: "Fresh Sweet Strawberries",
    variety: "Strawberry / Fraise",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 4,
    origin: "Île d’Orléans / Québec • Canada",
    storageTipFr: "Conserver au frigo non lavées avec un papier absorbant dans le contenant ajouré.",
    storageTipEn: "Store unwashed with paper towel in original vented clamshell in fridge.",
    calories: 32, protein: "0.7g", carbs: "7.7g", fat: "0.3g", fiber: "2.0g",
  },
  "4240": {
    nameFr: "Bleuets frais du Lac-Saint-Jean",
    nameEn: "Fresh Wild Blueberries",
    variety: "Blueberry / Bleuet",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 8,
    origin: "Lac-Saint-Jean / Québec • Canada",
    storageTipFr: "Conserver au frigo sans laver avant consommation.",
    storageTipEn: "Keep refrigerated and dry until ready to eat.",
    calories: 57, protein: "0.7g", carbs: "14.5g", fat: "0.3g", fiber: "2.4g",
  },
  "4252": {
    nameFr: "Framboises fraîches du Québec",
    nameEn: "Fresh Sweet Raspberries",
    variety: "Raspberry / Framboise",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 3,
    origin: "Québec • Canada",
    storageTipFr: "Très délicates : garder au froid sur papier absorbant, consommer rapidement.",
    storageTipEn: "Very delicate: store cold on paper towel, eat quickly.",
    calories: 52, protein: "1.2g", carbs: "11.9g", fat: "0.7g", fiber: "6.5g",
  },
  "4251": {
    nameFr: "Mûres fraîches juteuses",
    nameEn: "Fresh Blackberries",
    variety: "Blackberry / Mûre",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 4,
    origin: "Importé / Canada",
    storageTipFr: "Garder au réfrigérateur non lavées.",
    storageTipEn: "Refrigerate unwashed in original container.",
    calories: 43, protein: "1.4g", carbs: "9.6g", fat: "0.5g", fiber: "5.3g",
  },
  "4045": {
    nameFr: "Cerises douces rouges fraîches",
    nameEn: "Fresh Sweet Red Cherries",
    variety: "Sweet Cherry / Cerise",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 7,
    origin: "Colombie-Britannique / Washington",
    storageTipFr: "Conserver au froid dans un sac entrouvert, laver juste avant de déguster.",
    storageTipEn: "Keep cold in perforated bag, wash immediately before serving.",
    calories: 63, protein: "1.1g", carbs: "16g", fat: "0.2g", fiber: "2.1g",
  },
  "4022": {
    nameFr: "Raisins verts sans pépins",
    nameEn: "Green Seedless Grapes",
    variety: "Green Seedless Grapes",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 12,
    origin: "Californie / Chili",
    storageTipFr: "Conserver au bac à légumes dans leur sachet d’origine ventilé.",
    storageTipEn: "Store in original vented bag in crisper drawer.",
    calories: 69, protein: "0.7g", carbs: "18g", fat: "0.2g", fiber: "0.9g",
  },
  "4023": {
    nameFr: "Raisins rouges sans pépins",
    nameEn: "Red Seedless Grapes",
    variety: "Red Seedless Grapes",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 12,
    origin: "Californie / Chili",
    storageTipFr: "Garder au froid au réfrigérateur, croquants et sucrés.",
    storageTipEn: "Store cold in fridge crisper drawer.",
    calories: 69, protein: "0.7g", carbs: "18g", fat: "0.2g", fiber: "0.9g",
  },
  "4038": {
    nameFr: "Pêches jaunes fraîches juteuses",
    nameEn: "Fresh Sweet Yellow Peaches",
    variety: "Yellow Peach / Pêche",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 5,
    origin: "Ontario / Niagara • Canada No. 1",
    storageTipFr: "Mûrir à température ambiante tige vers le bas. Une fois souple, réfrigérer.",
    storageTipEn: "Ripen stem-side down at room temp. Refrigerate once soft.",
    calories: 39, protein: "0.9g", carbs: "9.5g", fat: "0.3g", fiber: "1.5g",
  },
  "4036": {
    nameFr: "Nectarines fraîches sucrées",
    nameEn: "Fresh Sweet Nectarines",
    variety: "Nectarine",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 5,
    origin: "Ontario / Californie",
    storageTipFr: "Garder sur le comptoir jusqu’à maturité parfumée.",
    storageTipEn: "Leave at room temperature until fragrant.",
    calories: 44, protein: "1.1g", carbs: "10.6g", fat: "0.3g", fiber: "1.7g",
  },
  "4040": {
    nameFr: "Prunes fraîches rouges / noires",
    nameEn: "Fresh Red / Black Plums",
    variety: "Plum / Prune",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 6,
    origin: "Ontario / Californie",
    storageTipFr: "Mûrir à température ambiante, puis réfrigérer pour prolonger.",
    storageTipEn: "Ripen at room temperature, then refrigerate.",
    calories: 46, protein: "0.7g", carbs: "11.4g", fat: "0.3g", fiber: "1.4g",
  },
  "4030": {
    nameFr: "Kiwis verts frais",
    nameEn: "Fresh Green Kiwifruit",
    variety: "Kiwi",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 14,
    origin: "Nouvelle-Zélande / Italie",
    storageTipFr: "Conserver à température ambiante ou au réfrigérateur jusqu’à 3 semaines.",
    storageTipEn: "Keep at room temp or in fridge for up to 3 weeks.",
    calories: 61, protein: "1.1g", carbs: "14.7g", fat: "0.5g", fiber: "3.0g",
  },
  "4445": {
    nameFr: "Grenade fraîche Wonderful à arilles rubis",
    nameEn: "Fresh Wonderful Pomegranate",
    variety: "Wonderful Pomegranate",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 30,
    origin: "Californie / Importé",
    storageTipFr: "Conserver entière au réfrigérateur jusqu’à un mois.",
    storageTipEn: "Stores well whole in the refrigerator up to a month.",
    calories: 83, protein: "1.7g", carbs: "18.7g", fat: "1.2g", fiber: "4.0g",
  },
  "4640": {
    nameFr: "Laitue romaine fraîche / Cœurs de romaine",
    nameEn: "Fresh Romaine Lettuce Hearts",
    variety: "Romaine Lettuce",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 10,
    origin: "Québec / Californie",
    storageTipFr: "Conserver dans le bac à légumes avec un essuie-tout pour absorber l’humidité.",
    storageTipEn: "Store in crisper drawer wrapped loosely with paper towel.",
    calories: 17, protein: "1.2g", carbs: "3.3g", fat: "0.3g", fiber: "2.1g",
  },
  "4061": {
    nameFr: "Laitue Iceberg croquante",
    nameEn: "Crisp Iceberg Lettuce",
    variety: "Iceberg Lettuce",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 14,
    origin: "Québec / Californie",
    storageTipFr: "Garder la tête entière au frigo dans son emballage.",
    storageTipEn: "Keep whole head cold in crisper drawer.",
    calories: 14, protein: "0.9g", carbs: "3.0g", fat: "0.1g", fiber: "1.2g",
  },
  "4090": {
    nameFr: "Bébés épinards frais",
    nameEn: "Fresh Baby Spinach",
    variety: "Spinach / Épinards",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 7,
    origin: "Québec / Ontario",
    storageTipFr: "Conserver bien au sec dans un contenant hermétique avec papier absorbant.",
    storageTipEn: "Keep completely dry in sealed container with paper towel.",
    calories: 23, protein: "2.9g", carbs: "3.6g", fat: "0.4g", fiber: "2.2g",
  },
  "4627": {
    nameFr: "Chou frisé / Kale vert frais",
    nameEn: "Fresh Green Curly Kale",
    variety: "Kale / Chou frisé",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 9,
    origin: "Québec • Aliments du Québec",
    storageTipFr: "Conserver au bac à légumes dans un sachet plastique entrouvert.",
    storageTipEn: "Store in crisper drawer in loose plastic bag.",
    calories: 49, protein: "4.3g", carbs: "8.8g", fat: "0.9g", fiber: "3.6g",
  },
  "4070": {
    nameFr: "Pied de céleri branche croquant",
    nameEn: "Crisp Celery Stalk",
    variety: "Celery / Céleri",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 18,
    origin: "Québec / Californie",
    storageTipFr: "Envelopper dans du papier aluminium au frigo pour garder le croquant des semaines.",
    storageTipEn: "Wrap in aluminum foil in fridge to stay crisp for weeks.",
    calories: 14, protein: "0.7g", carbs: "3.0g", fat: "0.2g", fiber: "1.6g",
  },
  "4080": {
    nameFr: "Asperges vertes fraîches",
    nameEn: "Fresh Green Asparagus",
    variety: "Asparagus / Asperge",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 7,
    origin: "Québec / Ontario • Canada No. 1",
    storageTipFr: "Placer les tiges debout dans 2 cm d’eau au frigo comme un bouquet de fleurs.",
    storageTipEn: "Stand stems upright in 1 inch of water in the fridge like flowers.",
    calories: 20, protein: "2.2g", carbs: "3.9g", fat: "0.1g", fiber: "2.1g",
  },
  "4069": {
    nameFr: "Chou vert frais entier",
    nameEn: "Fresh Green Cabbage",
    variety: "Green Cabbage",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 30,
    origin: "Québec • Aliments du Québec",
    storageTipFr: "Garder la tête entière au bac à légumes jusqu’à un mois.",
    storageTipEn: "Store whole head in crisper drawer up to a month.",
    calories: 25, protein: "1.3g", carbs: "5.8g", fat: "0.1g", fiber: "2.5g",
  },
  "4816": {
    nameFr: "Patates douces orangées (Yams)",
    nameEn: "Fresh Sweet Potatoes (Yams)",
    variety: "Sweet Potato / Patate douce",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 28,
    origin: "Caroline du Nord / Ontario",
    storageTipFr: "Conserver dans un endroit frais, sec et sombre. Ne jamais réfrigérer crue.",
    storageTipEn: "Store in cool, dark pantry. Never refrigerate raw.",
    calories: 86, protein: "1.6g", carbs: "20.1g", fat: "0.1g", fiber: "3.0g",
  },
  "4759": {
    nameFr: "Courge Butternut musquée",
    nameEn: "Butternut Squash",
    variety: "Butternut Squash",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 60,
    origin: "Québec • Aliments du Québec",
    storageTipFr: "Conserver entière à température ambiante dans un endroit sec jusqu’à 2-3 mois.",
    storageTipEn: "Store whole at room temperature in dry spot up to 3 months.",
    calories: 45, protein: "1.0g", carbs: "11.7g", fat: "0.1g", fiber: "2.0g",
  },
  "4066": {
    nameFr: "Haricots verts frais du Québec",
    nameEn: "Fresh Green Beans",
    variety: "Green Beans / Haricots",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 7,
    origin: "Québec • Aliments du Québec",
    storageTipFr: "Conserver non lavés dans un sac hermétique avec essuie-tout au bac à légumes.",
    storageTipEn: "Keep unwashed in perforated bag in crisper drawer.",
    calories: 31, protein: "1.8g", carbs: "7.0g", fat: "0.2g", fiber: "2.7g",
  },
  "4078": {
    nameFr: "Maïs sucré frais en épi (Blé d'Inde)",
    nameEn: "Fresh Sweet Corn on the Cob",
    variety: "Sweet Corn / Maïs",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 4,
    origin: "Québec • Aliments du Québec",
    storageTipFr: "Conserver dans les feuilles au frigo et consommer rapidement pour préserver le sucre.",
    storageTipEn: "Keep in husks in fridge; eat soon before sugars turn to starch.",
    calories: 86, protein: "3.2g", carbs: "19g", fat: "1.2g", fiber: "2.7g",
  },
  "4085": {
    nameFr: "Champignons blancs de Paris frais",
    nameEn: "Fresh White Button Mushrooms",
    variety: "White Button Mushroom",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 7,
    origin: "Québec / Ontario",
    storageTipFr: "Conserver dans un sac en papier brun au frigo pour éviter la condensation.",
    storageTipEn: "Store in brown paper bag in fridge to absorb excess moisture.",
    calories: 22, protein: "3.1g", carbs: "3.3g", fat: "0.3g", fiber: "1.0g",
  },

  // --- ASIAN & WORLD SPECIALTY PRODUCE ---
  "3040": {
    nameFr: "Fruit du dragon / Pitaya (Chair blanche ou rouge)",
    nameEn: "Fresh Dragon Fruit (Pitaya)",
    variety: "Dragon Fruit / Pitaya",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 8,
    origin: "Vietnam / Mexique • PLU #3040",
    storageTipFr: "Conserver à température ambiante jusqu’à maturité souple, puis réfrigérer.",
    storageTipEn: "Store at room temperature until slightly soft, then refrigerate.",
    calories: 60, protein: "1.2g", carbs: "13g", fat: "0g", fiber: "2.9g",
  },
  "4303": {
    nameFr: "Litchis frais sucrés",
    nameEn: "Fresh Sweet Lychees",
    variety: "Lychee / Litchi",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 7,
    origin: "Asie / Madagascar • PLU #4303",
    storageTipFr: "Envelopper dans du papier absorbant dans un sac au frigo pour garder la coque souple.",
    storageTipEn: "Wrap in paper towel in plastic bag in fridge to prevent browning.",
    calories: 66, protein: "0.8g", carbs: "16.5g", fat: "0.4g", fiber: "1.3g",
  },
  "4307": {
    nameFr: "Longanes frais (Œil de dragon)",
    nameEn: "Fresh Longan Fruit",
    variety: "Longan",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 8,
    origin: "Thaïlande / Vietnam • PLU #4307",
    storageTipFr: "Garder au réfrigérateur dans un sachet perforé.",
    storageTipEn: "Store in perforated bag in the refrigerator.",
    calories: 60, protein: "1.3g", carbs: "15g", fat: "0.1g", fiber: "1.1g",
  },
  "3042": {
    nameFr: "Ramboutan velu frais",
    nameEn: "Fresh Rambutan",
    variety: "Rambutan",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 6,
    origin: "Guatemala / Asie • PLU #3042",
    storageTipFr: "Conserver au frais au réfrigérateur dans un sachet.",
    storageTipEn: "Store cold in fridge wrapped in bag.",
    calories: 68, protein: "0.9g", carbs: "16g", fat: "0.2g", fiber: "1.4g",
  },
  "3041": {
    nameFr: "Durian frais entier",
    nameEn: "Fresh Whole Durian",
    variety: "Durian",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 5,
    origin: "Thaïlande / Malaisie • PLU #3041",
    storageTipFr: "Conserver dans un endroit bien aéré jusqu’à ouverture de l’écorce épineuse.",
    storageTipEn: "Store in ventilated area until shell cracks naturally.",
    calories: 147, protein: "1.5g", carbs: "27g", fat: "5.3g", fiber: "3.8g",
  },
  "3428": {
    nameFr: "Fruit du jacquier frais (Jackfruit)",
    nameEn: "Fresh Jackfruit",
    variety: "Jackfruit",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 7,
    origin: "Importé tropical • PLU #3428",
    storageTipFr: "Mûrir à température ambiante; réfrigérer les gousses après découpe.",
    storageTipEn: "Ripen at room temperature; refrigerate pods once sliced.",
    calories: 95, protein: "1.7g", carbs: "23g", fat: "0.6g", fiber: "1.5g",
  },
  "4259": {
    nameFr: "Carambole fraîche (Starfruit)",
    nameEn: "Fresh Starfruit (Carambola)",
    variety: "Starfruit",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 7,
    origin: "Importé tropical • PLU #4259",
    storageTipFr: "Mûrir jusqu’à ce que les arêtes brunissent légèrement, puis réfrigérer.",
    storageTipEn: "Leave at room temp until ribs slightly brown, then refrigerate.",
    calories: 31, protein: "1.0g", carbs: "6.7g", fat: "0.3g", fiber: "2.8g",
  },
  "4299": {
    nameFr: "Goyaves fraîches parfumées",
    nameEn: "Fresh Sweet Guavas",
    variety: "Guava",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 6,
    origin: "Mexique / Brésil • PLU #4299",
    storageTipFr: "Mûrir sur le comptoir. Déplacer au réfrigérateur une fois odorante et souple.",
    storageTipEn: "Ripen on counter until intensely fragrant and soft.",
    calories: 68, protein: "2.6g", carbs: "14g", fat: "1.0g", fiber: "5.4g",
  },
  "4427": {
    nameFr: "Kakis Fuyu doux (Persimmon)",
    nameEn: "Fuyu Sweet Persimmons",
    variety: "Fuyu Persimmon",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 14,
    origin: "Californie / Espagne • PLU #4427",
    storageTipFr: "Se consomme ferme et croquant comme une pomme. Garder à température ambiante.",
    storageTipEn: "Eaten firm and crisp like an apple. Store at room temperature.",
    calories: 70, protein: "0.6g", carbs: "18.6g", fat: "0.2g", fiber: "3.6g",
  },
  "4235": {
    nameFr: "Bananes plantains (Vertes / Mûres)",
    nameEn: "Fresh Green / Ripe Plantains",
    variety: "Plantain",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 14,
    origin: "Équateur / Colombie • PLU #4235",
    storageTipFr: "Conserver sur le comptoir. Se cuisine verte (bouillie/frite) ou noire (sucrée).",
    storageTipEn: "Store at room temp. Cook green for savory or black for sweet maduros.",
    calories: 122, protein: "1.3g", carbs: "32g", fat: "0.4g", fiber: "2.3g",
  },
  "4545": {
    nameFr: "Bok choy frais / Pak choï",
    nameEn: "Fresh Baby Bok Choy",
    variety: "Bok Choy",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 8,
    origin: "Serres du Québec / Ontario • PLU #4545",
    storageTipFr: "Conserver non lavé dans un sac plastique aéré au réfrigérateur.",
    storageTipEn: "Store unwashed in perforated plastic bag in crisper.",
    calories: 13, protein: "1.5g", carbs: "2.2g", fat: "0.2g", fiber: "1.0g",
  },
  "4548": {
    nameFr: "Gai Lan (Brocoli chinois frais)",
    nameEn: "Chinese Broccoli (Gai Lan)",
    variety: "Gai Lan",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 7,
    origin: "Québec / Ontario • PLU #4548",
    storageTipFr: "Conserver au bac à légumes avec un essuie-tout.",
    storageTipEn: "Store in crisper drawer loosely wrapped with paper towel.",
    calories: 26, protein: "1.2g", carbs: "4.8g", fat: "0.7g", fiber: "2.5g",
  },
  "4546": {
    nameFr: "Choy Sum (Yu Choy à petites fleurs)",
    nameEn: "Fresh Choy Sum (Yu Choy)",
    variety: "Choy Sum",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 6,
    origin: "Ontario / Québec • PLU #4546",
    storageTipFr: "Garder au froid au réfrigérateur et consommer rapidement pour préserver la tendreté.",
    storageTipEn: "Keep refrigerated in crisper and cook within a few days.",
    calories: 16, protein: "1.5g", carbs: "2.8g", fat: "0.2g", fiber: "1.8g",
  },
  "4552": {
    nameFr: "Chou chinois Napa (Wong Bok)",
    nameEn: "Napa Cabbage (Wong Bok)",
    variety: "Napa Cabbage",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 21,
    origin: "Québec • Aliments du Québec • PLU #4552",
    storageTipFr: "Emballer dans du film plastique au réfrigérateur; se conserve jusqu’à 3 semaines.",
    storageTipEn: "Wrap in plastic wrap in fridge crisper; keeps for 3-4 weeks.",
    calories: 16, protein: "1.2g", carbs: "3.2g", fat: "0.2g", fiber: "1.2g",
  },
  "4598": {
    nameFr: "Radis Daikon blanc asiatique",
    nameEn: "Fresh Daikon White Radish",
    variety: "Daikon Radish",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 21,
    origin: "Québec / Ontario • PLU #4598",
    storageTipFr: "Conserver dans un sac plastique au bac à légumes.",
    storageTipEn: "Store in sealed plastic bag in crisper drawer.",
    calories: 18, protein: "0.6g", carbs: "4.1g", fat: "0.1g", fiber: "1.6g",
  },
  "4732": {
    nameFr: "Racine de lotus fraîche",
    nameEn: "Fresh Lotus Root",
    variety: "Lotus Root",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 14,
    origin: "Importé asiatique • PLU #4732",
    storageTipFr: "Garder au réfrigérateur enveloppée d’un essuie-tout humide.",
    storageTipEn: "Store wrapped in damp paper towel in the fridge.",
    calories: 74, protein: "2.6g", carbs: "17g", fat: "0.1g", fiber: "4.9g",
  },
  "4782": {
    nameFr: "Melon amer frais (Bitter Melon / Ampalaya / Goya / Margose)",
    nameEn: "Fresh Bitter Melon (Ampalaya / Goya)",
    variety: "Bitter Melon / Ampalaya / Goya",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 7,
    origin: "Importé • PLU #4782",
    storageTipFr: "Conserver dans un sac en papier au réfrigérateur pour éviter l’humidité excessive.",
    storageTipEn: "Keep in a paper bag in the crisper drawer.",
    calories: 17, protein: "1.0g", carbs: "3.7g", fat: "0.2g", fiber: "2.8g",
  },
  "4794": {
    nameFr: "Racine de taro fraîche (Gabi)",
    nameEn: "Fresh Taro Root (Gabi)",
    variety: "Taro Root / Gabi",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 21,
    origin: "Importé • PLU #4794",
    storageTipFr: "Garder dans un endroit frais, sombre et sec. Ne jamais manger cru.",
    storageTipEn: "Keep in cool, dry, dark pantry. Must always be cooked before eating.",
    calories: 142, protein: "0.5g", carbs: "34.6g", fat: "0.1g", fiber: "5.1g",
  },
  "4645": {
    nameFr: "Champignons Enoki frais (Enokitake)",
    nameEn: "Fresh Enoki Mushrooms",
    variety: "Enoki Mushroom",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 10,
    origin: "Produit cultivé • PLU #4645",
    storageTipFr: "Garder dans son sachet d’origine au réfrigérateur.",
    storageTipEn: "Keep refrigerated in original breathable packaging.",
    calories: 37, protein: "2.7g", carbs: "7.8g", fat: "0.3g", fiber: "2.7g",
  },
  "4651": {
    nameFr: "Champignons Shiitake frais",
    nameEn: "Fresh Shiitake Mushrooms",
    variety: "Shiitake Mushroom",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 10,
    origin: "Québec / Ontario • PLU #4651",
    storageTipFr: "Conserver au réfrigérateur dans un sac en papier brun non fermé.",
    storageTipEn: "Store in open brown paper bag in the fridge.",
    calories: 34, protein: "2.2g", carbs: "6.8g", fat: "0.5g", fiber: "2.5g",
  },
  "4652": {
    nameFr: "Pleurote du panicaut (King Oyster / Trumpet)",
    nameEn: "King Oyster Mushrooms",
    variety: "King Oyster",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 12,
    origin: "Cultivé au Canada • PLU #4652",
    storageTipFr: "Garder au frais au frigo dans un emballage respirant.",
    storageTipEn: "Store in breathable bag in fridge.",
    calories: 35, protein: "3.3g", carbs: "5.0g", fat: "0.4g", fiber: "2.3g",
  },
  "4761": {
    nameFr: "Christophine fraîche (Chayote / Sayote / Chouchou)",
    nameEn: "Fresh Chayote Squash (Sayote)",
    variety: "Chayote / Sayote",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 21,
    origin: "Mexique / Costa Rica • PLU #4761",
    storageTipFr: "Conserver dans un sac plastique aéré au réfrigérateur jusqu’à un mois. Essentiel pour la soupe Tinola.",
    storageTipEn: "Store in perforated plastic bag in crisper up to 4 weeks. Key for Filipino Tinola.",
    calories: 19, protein: "0.8g", carbs: "4.5g", fat: "0.1g", fiber: "1.7g",
  },
  "4626": {
    nameFr: "Pois patate frais (Jicama / Singkamas)",
    nameEn: "Fresh Jicama (Singkamas)",
    variety: "Jicama / Singkamas",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 21,
    origin: "Mexique / Philippines • PLU #4626",
    storageTipFr: "Conserver dans un endroit sec et frais. Célèbre dans la chanson Bahay Kubo.",
    storageTipEn: "Keep whole root in dry cool pantry. Famed in Bahay Kubo song.",
    calories: 38, protein: "0.7g", carbs: "8.8g", fat: "0.1g", fiber: "4.9g",
  },
  "4655": {
    nameFr: "Gombos frais (Okra)",
    nameEn: "Fresh Okra (Gumbo)",
    variety: "Okra",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 5,
    origin: "Importé • PLU #4655",
    storageTipFr: "Conserver non lavé dans un sac en papier au bac à légumes.",
    storageTipEn: "Store unwashed in a paper bag in crisper drawer.",
    calories: 33, protein: "1.9g", carbs: "7.5g", fat: "0.2g", fiber: "3.2g",
  },
  "4769": {
    nameFr: "Courge Kabocha japonaise",
    nameEn: "Japanese Kabocha Squash",
    variety: "Kabocha Squash",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 90,
    origin: "Québec / Mexique • PLU #4769",
    storageTipFr: "Conserver entière à température ambiante dans un endroit sec jusqu’à 3 mois.",
    storageTipEn: "Store whole in cool dry place up to 3 months.",
    calories: 40, protein: "1.5g", carbs: "10g", fat: "0.1g", fiber: "1.5g",
  },
  "4430": {
    nameFr: "Mangoustan pourpre frais (Reine des fruits)",
    nameEn: "Fresh Purple Mangosteen",
    variety: "Mangosteen",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 8,
    origin: "Thaïlande / Asie tropicale • PLU #4430",
    storageTipFr: "Conserver à température ambiante fraîche (12°C). Ne pas trop refroidir au réfrigérateur.",
    storageTipEn: "Store at cool room temperature; avoid freezing or excessive chilling.",
    calories: 73, protein: "0.4g", carbs: "18g", fat: "0.6g", fiber: "1.8g",
  },
  "4397": {
    nameFr: "Fruit de la passion frais (Maracuja)",
    nameEn: "Fresh Passion Fruit (Maracuja)",
    variety: "Passion Fruit",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 10,
    origin: "Importé tropical • PLU #4397",
    storageTipFr: "Mûrir à température ambiante jusqu’à ce que la peau se ride, puis réfrigérer.",
    storageTipEn: "Store at room temp until skin wrinkles, then refrigerate.",
    calories: 97, protein: "2.2g", carbs: "23g", fat: "0.7g", fiber: "10.4g",
  },
  "4894": {
    nameFr: "Bâtons de citronnelle fraîche",
    nameEn: "Fresh Lemongrass Stalks",
    variety: "Lemongrass",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 18,
    origin: "Importé asiatique • PLU #4894",
    storageTipFr: "Envelopper serré dans une pellicule plastique au réfrigérateur.",
    storageTipEn: "Wrap tightly in plastic wrap in crisper drawer.",
    calories: 99, protein: "1.8g", carbs: "25g", fat: "0.5g", fiber: "0.0g",
  },
  "4886": {
    nameFr: "Basilic thaï frais aux tiges pourpres",
    nameEn: "Fresh Thai Basil",
    variety: "Thai Basil",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 6,
    origin: "Herbes fraîches asiatiques • PLU #4886",
    storageTipFr: "Mettre les tiges dans un verre d’eau sur le comptoir à température ambiante.",
    storageTipEn: "Keep stems in a glass of water on the counter like fresh flowers.",
    calories: 23, protein: "3.2g", carbs: "2.7g", fat: "0.6g", fiber: "1.6g",
  },
  "4819": {
    nameFr: "Manioc frais ciré (Yuca / Cassava)",
    nameEn: "Fresh Cassava Root (Yuca)",
    variety: "Cassava",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 14,
    origin: "Costa Rica / Colombie • PLU #4819",
    storageTipFr: "Garder au garde-manger au sec. Ne jamais manger cru (toujours bouillir ou frire).",
    storageTipEn: "Keep in cool dry pantry. Must always be peeled and cooked thoroughly.",
    calories: 160, protein: "1.4g", carbs: "38g", fat: "0.3g", fiber: "1.8g",
  },
  "4895": {
    nameFr: "Racine de galanga frais",
    nameEn: "Fresh Galangal Root",
    variety: "Galangal",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 21,
    origin: "Importé asiatique • PLU #4895",
    storageTipFr: "Envelopper dans du film étirable au réfrigérateur.",
    storageTipEn: "Wrap in cling film in fridge; slice frozen for broths.",
    calories: 71, protein: "1.0g", carbs: "15g", fat: "1.0g", fiber: "2.0g",
  },
  "4801": {
    nameFr: "Tomatilles fraîches avec enveloppe",
    nameEn: "Fresh Husk Tomatillos",
    variety: "Tomatillo",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 14,
    origin: "Mexique • PLU #4801",
    storageTipFr: "Conserver avec leur enveloppe dans un sac en papier au bac à légumes.",
    storageTipEn: "Keep in husks in paper bag in crisper drawer.",
    calories: 32, protein: "1.0g", carbs: "5.8g", fat: "1.0g", fiber: "1.9g",
  },
  "4690": {
    nameFr: "Piments Shishito doux à griller",
    nameEn: "Fresh Shishito Peppers",
    variety: "Shishito",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 10,
    origin: "Québec / Mexique • PLU #4690",
    storageTipFr: "Conserver au bac à légumes du réfrigérateur.",
    storageTipEn: "Store in crisper drawer in fridge.",
    calories: 20, protein: "0.9g", carbs: "4.6g", fat: "0.2g", fiber: "1.7g",
  },
  "4327": {
    nameFr: "Longanes frais (Œil de dragon)",
    nameEn: "Fresh Longan Fruit",
    variety: "Longan",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 10,
    origin: "Asie du Sud-Est • PLU #4327",
    storageTipFr: "Conserver dans un sac plastique perforé au réfrigérateur.",
    storageTipEn: "Store in perforated plastic bag in fridge.",
    calories: 60, protein: "1.3g", carbs: "15g", fat: "0.1g", fiber: "1.1g",
  },
  "4547": {
    nameFr: "Liseron d’eau frais (Ong Choy / Kangkong)",
    nameEn: "Fresh Water Spinach (Kangkong / Ong Choy)",
    variety: "Water Spinach / Kangkong",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 5,
    origin: "Québec / Ontario / Asie • PLU #4547",
    storageTipFr: "Envelopper dans un essuie-tout humide au bac à légumes. Ingrédient d’Adobong Kangkong et Sinigang.",
    storageTipEn: "Wrap in damp paper towel in crisper. Staple for Adobong Kangkong and Sinigang.",
    calories: 19, protein: "2.6g", carbs: "3.1g", fat: "0.2g", fiber: "2.1g",
  },
  "4549": {
    nameFr: "Pousses de pois doux (Dou Miao)",
    nameEn: "Fresh Pea Shoots (Dou Miao)",
    variety: "Pea Shoots",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 5,
    origin: "Serres du Québec / Ontario • PLU #4549",
    storageTipFr: "Garder au froid dans son emballage d’origine.",
    storageTipEn: "Keep cold in crisper; sauté lightly.",
    calories: 31, protein: "3.0g", carbs: "5.0g", fat: "0.4g", fiber: "2.0g",
  },
  "4257": {
    nameFr: "Fruit à pain frais (Breadfruit)",
    nameEn: "Fresh Breadfruit",
    variety: "Breadfruit",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 5,
    origin: "Caraïbes / Pacifique • PLU #4257",
    storageTipFr: "Conserver à température ambiante jusqu’à maturité, puis cuire.",
    storageTipEn: "Keep at room temp. Must be cooked before consumption.",
    calories: 103, protein: "1.1g", carbs: "27g", fat: "0.2g", fiber: "4.9g",
  },

  // --- FILIPINO PRODUCE & SPECIALTIES ---
  "4428": {
    nameFr: "Calamansi frais (Limette philippine / Calamondin)",
    nameEn: "Fresh Calamansi (Philippine Lime)",
    variety: "Calamansi",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 14,
    origin: "Philippines / Asie • PLU #4428",
    storageTipFr: "Conserver au bac à légumes du réfrigérateur. Indispensable pour sinigang et marinades.",
    storageTipEn: "Store in crisper drawer in fridge. Staple for sawsawan and marinades.",
    calories: 12, protein: "0.4g", carbs: "2.8g", fat: "0.1g", fiber: "0.8g",
  },
  "4814": {
    nameFr: "Ube frais (Igname pourpre des Philippines)",
    nameEn: "Fresh Purple Yam (Ube)",
    variety: "Ube",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 21,
    origin: "Philippines • PLU #4814",
    storageTipFr: "Conserver dans un garde-manger sec, frais et sombre. Ne pas réfrigérer cru.",
    storageTipEn: "Keep in dry, dark pantry. Must always be boiled or steamed thoroughly.",
    calories: 140, protein: "1.5g", carbs: "31g", fat: "0.2g", fiber: "4.0g",
  },
  "4234": {
    nameFr: "Banane Saba fraîche (Banane à cuire / Cardaba)",
    nameEn: "Fresh Saba Bananas (Cooking Banana)",
    variety: "Saba Banana",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 10,
    origin: "Philippines • PLU #4234",
    storageTipFr: "Garder sur le comptoir. Ingrédient clé du Turon, Nilaga et Halo-Halo.",
    storageTipEn: "Store at room temperature. Key ingredient for Turon, Pochero and Nilaga.",
    calories: 120, protein: "1.3g", carbs: "31g", fat: "0.3g", fiber: "2.5g",
  },
  "4880": {
    nameFr: "Sitaw frais (Haricots longs philippins / Yardlong beans)",
    nameEn: "Fresh Yardlong Beans (Sitaw)",
    variety: "Sitaw",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 7,
    origin: "Serres / Importé • PLU #4880",
    storageTipFr: "Envelopper dans un sac plastique aéré au bac à légumes. Idéal pour Adobong Sitaw et Sinigang.",
    storageTipEn: "Store in perforated bag in crisper. Cut into 2-inch segments for cooking.",
    calories: 47, protein: "2.8g", carbs: "8.3g", fat: "0.4g", fiber: "3.6g",
  },
  "4882": {
    nameFr: "Malunggay frais (Feuilles de moringa philippines)",
    nameEn: "Fresh Moringa Leaves (Malunggay)",
    variety: "Malunggay",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 5,
    origin: "Serres / Importé philippin • PLU #4882",
    storageTipFr: "Enlever les tiges ligneuses et conserver les petites feuilles au froid dans du papier absorbant.",
    storageTipEn: "Strip leaves from woody stems; store in paper towel in fridge. Great for Tinola.",
    calories: 64, protein: "9.4g", carbs: "8.2g", fat: "1.4g", fiber: "2.0g",
  },
  "4883": {
    nameFr: "Puso ng Saging (Fleur / Cœur de bananier)",
    nameEn: "Banana Blossom (Puso ng Saging)",
    variety: "Banana Blossom",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 8,
    origin: "Philippines / Asie • PLU #4883",
    storageTipFr: "Garder au frigo dans un sac scellé. Tremper les tranches dans de l’eau salée citronnée avant cuisson.",
    storageTipEn: "Keep refrigerated. Soak sliced petals in salted lemon water to prevent browning.",
    calories: 51, protein: "1.6g", carbs: "9.9g", fat: "0.6g", fiber: "5.7g",
  },
  "4298": {
    nameFr: "Guyabano frais (Corossol doux / Soursop)",
    nameEn: "Fresh Soursop (Guyabano)",
    variety: "Guyabano",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 6,
    origin: "Philippines / Tropiques • PLU #4298",
    storageTipFr: "Mûrir à température ambiante jusqu’à chair souple, puis réfrigérer.",
    storageTipEn: "Ripen at room temperature until soft to the touch, then refrigerate.",
    calories: 66, protein: "1.0g", carbs: "16.8g", fat: "0.3g", fiber: "3.3g",
  },
  "4258": {
    nameFr: "Atis frais (Pomme cannelle / Sugar Apple)",
    nameEn: "Fresh Sugar Apple (Atis)",
    variety: "Atis",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 5,
    origin: "Philippines / Asie • PLU #4258",
    storageTipFr: "Garder à température ambiante jusqu’à ce que les segments s’écartent légèrement.",
    storageTipEn: "Store at room temp until knobs yield softly to gentle pressure.",
    calories: 94, protein: "2.1g", carbs: "23.6g", fat: "0.3g", fiber: "4.4g",
  },
  "3430": {
    nameFr: "Santol frais (Faux mangoustan / Cotton Fruit)",
    nameEn: "Fresh Cotton Fruit (Santol)",
    variety: "Santol",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 7,
    origin: "Philippines • PLU #3430",
    storageTipFr: "Garder à température ambiante. Se consomme frais ou en Ginataang Santol.",
    storageTipEn: "Keep at room temp. Enjoy fresh arils or cook rind in coconut milk.",
    calories: 50, protein: "0.7g", carbs: "12g", fat: "0.2g", fiber: "2.1g",
  },
  "4261": {
    nameFr: "Chico frais (Sapotille philippine / Sapodilla)",
    nameEn: "Fresh Sapodilla (Chico)",
    variety: "Chico",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 6,
    origin: "Philippines / Mexique • PLU #4261",
    storageTipFr: "Garder sur le comptoir jusqu’à chair tendre; goût doux de cassonade et malt.",
    storageTipEn: "Ripen on counter until soft; distinct brown sugar caramel flavor.",
    calories: 83, protein: "0.4g", carbs: "20g", fat: "1.1g", fiber: "5.3g",
  },
  "3432": {
    nameFr: "Lanzones frais (Langsat philippin)",
    nameEn: "Fresh Lanzones (Langsat)",
    variety: "Lanzones",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 7,
    origin: "Philippines • PLU #3432",
    storageTipFr: "Conserver les grappes au réfrigérateur dans un sachet perforé.",
    storageTipEn: "Store clusters in perforated bag in fridge.",
    calories: 57, protein: "0.8g", carbs: "14g", fat: "0.1g", fiber: "1.2g",
  },
  "3435": {
    nameFr: "Kamias frais (Bilimbi acide des Philippines)",
    nameEn: "Fresh Bilimbi (Kamias)",
    variety: "Kamias",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 5,
    origin: "Philippines / Asie • PLU #3435",
    storageTipFr: "Conserver au réfrigérateur. Utilisé comme agent acidifiant dans le sinigang et paksiw.",
    storageTipEn: "Store in fridge. Traditional souring fruit for sinigang and fish paksiw.",
    calories: 10, protein: "0.6g", carbs: "2.5g", fat: "0.1g", fiber: "1.0g",
  },
  "4762": {
    nameFr: "Patola fraîche (Courge éponge / Luffa)",
    nameEn: "Fresh Sponge Gourd (Patola)",
    variety: "Patola",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 8,
    origin: "Serres / Importé • PLU #4762",
    storageTipFr: "Peler les arêtes dures et couper en rondelles pour la soupe Miswa.",
    storageTipEn: "Peel ridges and slice for traditional Miswa soup with meatballs.",
    calories: 20, protein: "1.2g", carbs: "4.3g", fat: "0.2g", fiber: "1.1g",
  },
  "4763": {
    nameFr: "Upo frais (Calebasse blanche / Bottle Gourd)",
    nameEn: "Fresh Bottle Gourd (Upo)",
    variety: "Upo",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 14,
    origin: "Serres / Importé • PLU #4763",
    storageTipFr: "Conserver entier au frigo. Délicieux sauté à l’ail et aux crevettes (Ginisang Upo).",
    storageTipEn: "Keep refrigerated whole. Sauté with garlic and shrimp for Ginisang Upo.",
    calories: 14, protein: "0.6g", carbs: "3.4g", fat: "0.0g", fiber: "0.5g",
  },
  "4768": {
    nameFr: "Courge Kalabasa philippine (Calabaza)",
    nameEn: "Philippine Calabaza Squash (Kalabasa)",
    variety: "Kalabasa",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 60,
    origin: "Philippines / Amériques • PLU #4768",
    storageTipFr: "Garder entière au garde-manger. Indispensable pour le Pinakbet authentique.",
    storageTipEn: "Store whole at room temperature. Essential for authentic Pinakbet.",
    calories: 36, protein: "1.0g", carbs: "9.0g", fat: "0.2g", fiber: "1.4g",
  },
  "4881": {
    nameFr: "Talbos ng Kamote (Feuilles de patate douce)",
    nameEn: "Sweet Potato Leaves (Talbos ng Kamote)",
    variety: "Talbos ng Kamote",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 5,
    origin: "Serres locales • PLU #4881",
    storageTipFr: "Conserver au bac à légumes. Se blanchit pour salade aux tomates et bagoong.",
    storageTipEn: "Store in crisper. Blanch for traditional salad with tomatoes and calamansi.",
    calories: 41, protein: "3.1g", carbs: "7.0g", fat: "0.3g", fiber: "1.9g",
  },
  "4692": {
    nameFr: "Siling Labuyo frais (Piment oiseau philippin)",
    nameEn: "Fresh Siling Labuyo (Philippine Bird's Eye Chili)",
    variety: "Siling Labuyo",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 14,
    origin: "Philippines / Serres • PLU #4692",
    storageTipFr: "Conserver dans un bocal ou sac au frigo. Piment très piquant (80 000-100 000 SHU).",
    storageTipEn: "Store in dry container in fridge. Very spicy (80k-100k SHU), used for dipping sauces.",
    calories: 40, protein: "1.9g", carbs: "8.8g", fat: "0.4g", fiber: "1.5g",
  },
  "4312": {
    nameFr: "Mangue Carabao philippine (Manila Super Mango)",
    nameEn: "Philippine Carabao Mango (Manila Mango)",
    variety: "Carabao Mango",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 7,
    origin: "Guimaras / Zambales, Philippines • PLU #4312",
    storageTipFr: "Reconnue au livre Guinness comme la mangue la plus sucrée du monde. Mûrir sur le comptoir.",
    storageTipEn: "Guinness World Record sweetest mango. Ripen at room temp until aromatic and golden.",
    calories: 60, protein: "0.8g", carbs: "15g", fat: "0.4g", fiber: "1.6g",
  },

  // --- TROPICAL & EXOTIC FRUITS ---
  "4051": {
    nameFr: "Mangue rouge fraîche (Tommy Atkins / Kent)",
    nameEn: "Fresh Red Mango (Tommy Atkins / Kent)",
    variety: "Tommy Atkins / Kent",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 7,
    origin: "Mexique / Pérou / Brésil",
    storageTipFr: "Mûrir sur le comptoir à température ambiante. Transférer au réfrigérateur une fois souple.",
    storageTipEn: "Ripen at room temperature on counter. Refrigerate once slightly soft to touch.",
    calories: 60, protein: "0.8g", carbs: "15g", fat: "0.4g", fiber: "1.6g",
  },
  "4959": {
    nameFr: "Grosse mangue rouge tropicale",
    nameEn: "Large Red Tropical Mango",
    variety: "Large Red",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 7,
    origin: "Importé",
    storageTipFr: "Conserver sur le comptoir. Délicieuse en smoothie ou salade de fruits.",
    storageTipEn: "Keep at room temperature until fragrant and ripe.",
    calories: 65, protein: "0.8g", carbs: "16g", fat: "0.4g", fiber: "1.7g",
  },
  "4958": {
    nameFr: "Mangue Ataulfo (Mangue miel mexicaine)",
    nameEn: "Ataulfo Honey Mango",
    variety: "Ataulfo (Honey / Champagne)",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 6,
    origin: "Mexique • PLU #4958",
    storageTipFr: "Prête à consommer lorsque la peau devient dorée et légèrement fripée.",
    storageTipEn: "Ready to eat when golden yellow and skin slightly wrinkles.",
    calories: 62, protein: "0.9g", carbs: "15g", fat: "0.3g", fiber: "1.8g",
  },
  "3114": {
    nameFr: "Mangue verte / mûre à cuisiner",
    nameEn: "Green / Cooking Mango",
    variety: "Green / Keitt",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 8,
    origin: "Importé",
    storageTipFr: "Idéale pour salades thaïes ou chutneys épicés.",
    storageTipEn: "Ideal for salads, chutneys, or ripening slowly.",
    calories: 58, protein: "0.7g", carbs: "14g", fat: "0.3g", fiber: "1.5g",
  },
  "4011": {
    nameFr: "Bananes jaunes fraîches",
    nameEn: "Fresh Yellow Bananas",
    variety: "Cavendish",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 5,
    origin: "Équateur / Costa Rica / Colombie",
    storageTipFr: "Garder sur le comptoir à l'air libre. Ne pas réfrigérer entière pour éviter le noircissement.",
    storageTipEn: "Store on countertop. Do not refrigerate whole peel to avoid browning.",
    calories: 89, protein: "1.1g", carbs: "23g", fat: "0.3g", fiber: "2.6g",
  },
  "4046": {
    nameFr: "Avocats Hass réguliers",
    nameEn: "Hass Avocados (Medium)",
    variety: "Hass",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 6,
    origin: "Mexique",
    storageTipFr: "Mûrir sur le comptoir. Placer au frigo une fois la peau foncée et souple.",
    storageTipEn: "Ripen on counter. Move to fridge once dark and soft.",
    calories: 160, protein: "2g", carbs: "9g", fat: "15g", fiber: "7g",
  },
  "4225": {
    nameFr: "Gros avocats Hass",
    nameEn: "Large Hass Avocados",
    variety: "Hass Jumbo",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 6,
    origin: "Mexique / Pérou",
    storageTipFr: "Mûrir à l'air libre. Arroser de jus de lime si coupé en deux.",
    storageTipEn: "Store cut side with lime juice in airtight container.",
    calories: 220, protein: "2.7g", carbs: "12g", fat: "20g", fiber: "9g",
  },
  "4432": {
    nameFr: "Ananas frais doré (Golden Ripe)",
    nameEn: "Fresh Golden Pineapple",
    variety: "MD2 Extra Sweet",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 6,
    origin: "Costa Rica",
    storageTipFr: "Garder sur le comptoir. Une fois tranché, conserver au frigo dans un contenant hermétique.",
    storageTipEn: "Keep stem-down on counter. Refrigerate once cut.",
    calories: 50, protein: "0.5g", carbs: "13g", fat: "0.1g", fiber: "1.4g",
  },
  "4032": {
    nameFr: "Pastèque entière sans pépins (Melon d'eau)",
    nameEn: "Seedless Watermelon",
    variety: "Seedless",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 10,
    origin: "Canada (Ontario) / États-Unis",
    storageTipFr: "Conserver entière à température ambiante. Réfrigérer immédiatement après découpe.",
    storageTipEn: "Store whole at room temperature. Refrigerate once sliced.",
    calories: 30, protein: "0.6g", carbs: "8g", fat: "0.2g", fiber: "0.4g",
  },
  "4050": {
    nameFr: "Cantaloup frais (Melon brodé)",
    nameEn: "Fresh Cantaloupe",
    variety: "Cantaloupe",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 7,
    origin: "Canada / Importé",
    storageTipFr: "Mûrir sur le comptoir. Réfrigérer dès qu'il dégage un parfum sucré.",
    storageTipEn: "Countertop until aromatic, then refrigerate.",
    calories: 34, protein: "0.8g", carbs: "8g", fat: "0.2g", fiber: "0.9g",
  },

  // --- APPLES (Canadian & Quebec Orchard Varieties) ---
  "4152": {
    nameFr: "Pommes McIntosh du Québec",
    nameEn: "Quebec McIntosh Apples",
    variety: "McIntosh (Pommes du Québec)",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 30,
    origin: "Québec, Canada",
    storageTipFr: "Conserver dans le bac à légumes à faible humidité du réfrigérateur.",
    storageTipEn: "Keep in the crisper drawer of your refrigerator.",
    calories: 52, protein: "0.3g", carbs: "14g", fat: "0.2g", fiber: "2.4g",
  },
  "4133": {
    nameFr: "Pommes Gala fraîches",
    nameEn: "Fresh Gala Apples",
    variety: "Gala (Canada No. 1)",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 28,
    origin: "Canada (Québec / Ontario)",
    storageTipFr: "Conserver au frais pour préserver le croquant sucré.",
    storageTipEn: "Refrigerate to preserve natural crisp sweetness.",
    calories: 52, protein: "0.3g", carbs: "14g", fat: "0.2g", fiber: "2.4g",
  },
  "4173": {
    nameFr: "Pommes Honeycrisp de l'Ontario / Québec",
    nameEn: "Honeycrisp Apples",
    variety: "Honeycrisp",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 35,
    origin: "Canada",
    storageTipFr: "Pomme extra croquante et juteuse. Réfrigérer en permanence.",
    storageTipEn: "Extra crisp and juicy. Keep constantly chilled.",
    calories: 57, protein: "0.3g", carbs: "15g", fat: "0.2g", fiber: "2.5g",
  },
  "4124": {
    nameFr: "Pommes Cortland du Québec (Idéales en cuisine)",
    nameEn: "Cortland Apples (Quebec)",
    variety: "Cortland",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 28,
    origin: "Québec, Canada",
    storageTipFr: "La chair ne brunit pas rapidement à l'air libre. Parfaite pour salades et tartes.",
    storageTipEn: "Flesh resists browning. Superb for salads and pies.",
    calories: 50, protein: "0.3g", carbs: "13g", fat: "0.2g", fiber: "2.2g",
  },
  "4131": {
    nameFr: "Pommes Fuji croquantes",
    nameEn: "Fuji Apples",
    variety: "Fuji",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 35,
    origin: "Canada / Importé",
    storageTipFr: "Très longue conservation au réfrigérateur.",
    storageTipEn: "Long storage life when refrigerated in crisper.",
    calories: 55, protein: "0.3g", carbs: "15g", fat: "0.2g", fiber: "2.4g",
  },
  "3438": {
    nameFr: "Pommes Ambrosia de la Colombie-Britannique",
    nameEn: "Ambrosia Apples (BC Canada)",
    variety: "Ambrosia",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 30,
    origin: "Colombie-Britannique, Canada",
    storageTipFr: "Variété canadienne douce et mielleuse à chair crème.",
    storageTipEn: "Canadian sweet variety discovered in British Columbia.",
    calories: 54, protein: "0.3g", carbs: "14g", fat: "0.2g", fiber: "2.4g",
  },

  // --- CITRUS & BERRIES ---
  "4053": {
    nameFr: "Citrons jaunes frais",
    nameEn: "Fresh Yellow Lemons",
    variety: "Eureka / Lisbon",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 21,
    origin: "États-Unis / Espagne",
    storageTipFr: "Au frigo dans un sac scellé pour conserver jusqu'à 3 semaines de jus.",
    storageTipEn: "Store in a sealed bag in the crisper drawer for up to 3 weeks.",
    calories: 29, protein: "1.1g", carbs: "9g", fat: "0.3g", fiber: "2.8g",
  },
  "4048": {
    nameFr: "Limes fraîches (Citrons verts)",
    nameEn: "Fresh Limes",
    variety: "Persian Lime",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 21,
    origin: "Mexique",
    storageTipFr: "Conserver au bac à légumes pour éviter le dessèchement de l'écorce.",
    storageTipEn: "Refrigerate in crisper drawer to avoid skin drying out.",
    calories: 30, protein: "0.7g", carbs: "11g", fat: "0.2g", fiber: "2.8g",
  },
  "4012": {
    nameFr: "Oranges Navel douces sans pépins",
    nameEn: "Navel Oranges",
    variety: "Navel",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 21,
    origin: "Californie / Floride",
    storageTipFr: "Garder au frigo ou sur le comptoir si consommées dans les 4 jours.",
    storageTipEn: "Refrigerate for longevity, or keep on counter if eating soon.",
    calories: 47, protein: "0.9g", carbs: "12g", fat: "0.1g", fiber: "2.4g",
  },

  // --- CANADIAN & POPULAR VEGETABLES ---
  "4065": {
    nameFr: "Tomates de serre sur vigne (Savoura / Mirabel)",
    nameEn: "Greenhouse Vine Tomatoes",
    variety: "Vine Ripe (Serres du Québec)",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 7,
    origin: "Québec, Canada",
    storageTipFr: "Garder sur le comptoir pour préserver toute la saveur et texture juteuse.",
    storageTipEn: "Keep stem-on on counter. Never refrigerate raw vine tomatoes.",
    calories: 18, protein: "0.9g", carbs: "3.9g", fat: "0.2g", fiber: "1.2g",
  },
  "4087": {
    nameFr: "Tomates italiennes Roma",
    nameEn: "Roma Plum Tomatoes",
    variety: "Roma",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 7,
    origin: "Canada / Mexique",
    storageTipFr: "Chair dense, idéale pour coulis, sauces et pâtes.",
    storageTipEn: "Meaty flesh ideal for slow-cooked pasta sauces and canning.",
    calories: 18, protein: "0.9g", carbs: "3.9g", fat: "0.2g", fiber: "1.2g",
  },
  "4062": {
    nameFr: "Concombre anglais sans pépins",
    nameEn: "English Seedless Cucumber",
    variety: "English Greenhouse",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 8,
    origin: "Québec / Ontario, Canada",
    storageTipFr: "Conserver dans sa pellicule plastique d'origine dans le bac à légumes.",
    storageTipEn: "Keep in original plastic wrap in crisper drawer to retain moisture.",
    calories: 15, protein: "0.7g", carbs: "3.6g", fat: "0.1g", fiber: "0.5g",
  },
  "4562": {
    nameFr: "Carottes fraîches en vrac ou sac",
    nameEn: "Fresh Carrots",
    variety: "Canada No. 1",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 30,
    origin: "Québec, Canada (Terres Noires)",
    storageTipFr: "Conserver au bac à légumes dans un sac perforé avec un essuie-tout.",
    storageTipEn: "Store in perforated bag with a paper towel in crisper drawer.",
    calories: 41, protein: "0.9g", carbs: "10g", fat: "0.2g", fiber: "2.8g",
  },
  "4060": {
    nameFr: "Couronnes de brocoli frais",
    nameEn: "Fresh Broccoli Crowns",
    variety: "Crown Cut",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 6,
    origin: "Canada (Québec) / États-Unis",
    storageTipFr: "Conserver au réfrigérateur non lavé dans un sac plastique entrouvert.",
    storageTipEn: "Keep unwashed in loose plastic bag in refrigerator crisper.",
    calories: 34, protein: "2.8g", carbs: "7g", fat: "0.4g", fiber: "2.6g",
  },
  "4079": {
    nameFr: "Chou-fleur blanc frais",
    nameEn: "White Cauliflower",
    variety: "White Crown",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 9,
    origin: "Canada / États-Unis",
    storageTipFr: "Conserver tige vers le haut au réfrigérateur pour éviter l'humidité.",
    storageTipEn: "Store stem-side up in fridge to prevent moisture accumulation.",
    calories: 25, protein: "1.9g", carbs: "5g", fat: "0.3g", fiber: "2g",
  },
  "4072": {
    nameFr: "Pommes de terre Russet du Québec",
    nameEn: "Quebec Russet Baking Potatoes",
    variety: "Russet Burbank",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 35,
    origin: "Québec, Canada",
    storageTipFr: "Conserver dans un garde-manger frais, sec et sombre. Ne pas réfrigérer.",
    storageTipEn: "Store in a cool, dark, ventilated pantry. Never refrigerate.",
    calories: 77, protein: "2g", carbs: "17g", fat: "0.1g", fiber: "2.1g",
  },
  "4727": {
    nameFr: "Pommes de terre jaunes grelots / Yukon Gold",
    nameEn: "Yukon Gold / Yellow Potatoes",
    variety: "Yukon Gold",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 30,
    origin: "Canada (Ontario / Québec)",
    storageTipFr: "Chair jaune beurrée, excellente en purée ou rôtie au four.",
    storageTipEn: "Classic Canadian yellow-fleshed potato invented at U of Guelph.",
    calories: 70, protein: "1.9g", carbs: "16g", fat: "0.1g", fiber: "1.8g",
  },
  "4088": {
    nameFr: "Poivrons doux rouges",
    nameEn: "Red Sweet Bell Peppers",
    variety: "Bell Pepper",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 10,
    origin: "Canada / Mexique",
    storageTipFr: "Conserver au bac à légumes bien sec.",
    storageTipEn: "Store dry in vegetable crisper drawer.",
    calories: 31, protein: "1g", carbs: "6g", fat: "0.3g", fiber: "2.1g",
  },
  "4093": {
    nameFr: "Oignons jaunes à cuire",
    nameEn: "Yellow Cooking Onions",
    variety: "Yellow Storage",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 45,
    origin: "Québec, Canada",
    storageTipFr: "Conserver dans un panier ventilé dans un endroit sombre et sec.",
    storageTipEn: "Keep in a cool, dry, well-ventilated spot away from potatoes.",
    calories: 40, protein: "1.1g", carbs: "9g", fat: "0.1g", fiber: "1.7g",
  },
  "4068": {
    nameFr: "Oignons verts (Échalotes fraîches)",
    nameEn: "Green Onions / Scallions",
    variety: "Scallions",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 10,
    origin: "Canada / Mexique",
    storageTipFr: "Placer les racines dans un petit verre d'eau au frigo ou envelopper dans un linge humide.",
    storageTipEn: "Stand upright in a glass with 1 inch of water in the fridge.",
    calories: 32, protein: "1.8g", carbs: "7g", fat: "0.2g", fiber: "2.6g",
  },
  "4608": {
    nameFr: "Ail blanc frais en bulbe",
    nameEn: "Fresh Garlic Bulbs",
    variety: "Softneck / Hardneck",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Pantry",
    shelfLifeDays: 60,
    origin: "Canada / Espagne",
    storageTipFr: "Conserver à l'air libre dans un endroit tempéré et sec.",
    storageTipEn: "Store at room temperature in a mesh bag or garlic keeper.",
    calories: 149, protein: "6.4g", carbs: "33g", fat: "0.5g", fiber: "2.1g",
  },
  "4648": {
    nameFr: "Champignons Cremini (Bébé Bella)",
    nameEn: "Cremini / Baby Bella Mushrooms",
    variety: "Cremini",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 7,
    origin: "Canada",
    storageTipFr: "Saveur plus boisée et terreuse que le champignon blanc.",
    storageTipEn: "Earthier flavor. Keep dry in paper bag.",
    calories: 22, protein: "2.5g", carbs: "3.9g", fat: "0.1g", fiber: "1.2g",
  },
  "4067": {
    nameFr: "Courgettes vertes (Zucchini)",
    nameEn: "Green Zucchini",
    variety: "Green Zucchini",
    category: "Produce",
    categoryFr: "Produits frais",
    location: "Fridge",
    shelfLifeDays: 7,
    origin: "Canada (Québec) / Mexique",
    storageTipFr: "Conserver au bac à légumes sans emballage étanche.",
    storageTipEn: "Store in crisper drawer in loose plastic wrap.",
    calories: 17, protein: "1.2g", carbs: "3.1g", fat: "0.3g", fiber: "1g",
  },
};

// ============================================================================
// 2. CANADIAN NUTRIENT FILE (CNF) & BILINGUAL CANADIAN RETAIL STAPLES
// ============================================================================
export const CANADIAN_NUTRIENT_FILE_CATALOG = [
  // --- DAIRY & EGGS (Canadian Standards: Homo, 2%, 1%, Skim, Butter, Cheese) ---
  {
    code: "CNF_DAIRY_01",
    upc: "068700011039",
    nameFr: "Lait 2% partiellement écrémé canadien",
    nameEn: "Canadian 2% Partly Skimmed Milk",
    brand: "Québon / Sealtest / Natrel / Lactantia",
    category: "Dairy & Eggs",
    categoryFr: "Produits laitiers & œufs",
    location: "Fridge",
    unopenedShelfLifeDays: 16,
    openedShelfLifeDays: 7,
    origin: "Lait 100% canadien (Logo Vache Bleue)",
    badges: ["Lait 100% canadien", "Vitamines A & D", "Aliments du Québec"],
    nutrition: { serving: "250 mL (1 tasse)", calories: 130, protein: "9g", carbs: "12g", fat: "5g", calcium: "300mg" },
    storageTipFr: "Conserver sur les tablettes intérieures du réfrigérateur à 4°C (éviter la porte).",
    storageTipEn: "Keep on middle fridge shelves at 4°C rather than inside door for stable temp.",
  },
  {
    code: "CNF_DAIRY_02",
    upc: "055653670014",
    nameFr: "Beurre salé de crème fraîche canadienne",
    nameEn: "Canadian Salted Butter",
    brand: "Lactantia / Gay Lea / Natrel",
    category: "Dairy & Eggs",
    categoryFr: "Produits laitiers & œufs",
    location: "Fridge",
    unopenedShelfLifeDays: 90,
    openedShelfLifeDays: 30,
    monthsFrozenShelfLife: 12,
    origin: "Canada (Crème pasteurisée 100% canadienne)",
    badges: ["Crème 100% canadienne", "Sans colorant artificiel"],
    nutrition: { serving: "10g (2 c. à thé)", calories: 70, protein: "0.1g", carbs: "0g", fat: "8g", sodium: "65mg" },
    storageTipFr: "Conserver au frigo bien emballé. Se congèle parfaitement jusqu'à 1 an.",
    storageTipEn: "Keep tightly wrapped. Can be frozen for up to 1 year.",
  },
  {
    code: "CNF_DAIRY_03",
    upc: "068200000155",
    nameFr: "Fromage Cheddar vieilli canadien",
    nameEn: "Canadian Aged Cheddar Cheese",
    brand: "Black Diamond / Armstrong / Perron / Île-aux-Grues",
    category: "Dairy & Eggs",
    categoryFr: "Produits laitiers & œufs",
    location: "Fridge",
    unopenedShelfLifeDays: 120,
    openedShelfLifeDays: 28,
    origin: "Québec / Ontario, Canada",
    badges: ["Lait canadien", "Sans lactose naturel", "Riche en calcium"],
    nutrition: { serving: "30g", calories: 120, protein: "7g", carbs: "0g", fat: "10g", calcium: "200mg" },
    storageTipFr: "Envelopper dans du papier ciré ou parchemin puis dans un sac hermétique.",
    storageTipEn: "Wrap in wax or parchment paper, then place in an airtight bag.",
  },
  {
    code: "CNF_DAIRY_04",
    upc: "067000001018",
    nameFr: "Fromage en grains frais du jour (Cheddar frais)",
    nameEn: "Fresh Cheese Curds (Squeaky Curds)",
    brand: "P'tit Québec / St-Guillaume / Victoriaville / Boivin",
    category: "Dairy & Eggs",
    categoryFr: "Produits laitiers & œufs",
    location: "Pantry",
    unopenedShelfLifeDays: 2,
    openedShelfLifeDays: 7,
    origin: "Québec, Canada",
    badges: ["Aliments du Québec", "Fait au Québec", "Tradition poutine"],
    nutrition: { serving: "50g", calories: 190, protein: "13g", carbs: "1g", fat: "15g", sodium: "380mg" },
    storageTipFr: "Garder à température ambiante le 1er jour pour conserver le 'squick-squick'. Réfrigérer ensuite.",
    storageTipEn: "Keep at room temp day 1 for optimal squeak. Refrigerate thereafter.",
  },
  {
    code: "CNF_DAIRY_05",
    upc: "064541234567",
    nameFr: "Gros œufs blancs canadiens Calibre A",
    nameEn: "Canadian Grade A Large White Eggs",
    brand: "Nutri / Burnbrae / Sélection / Compliments",
    category: "Dairy & Eggs",
    categoryFr: "Produits laitiers & œufs",
    location: "Fridge",
    unopenedShelfLifeDays: 35,
    openedShelfLifeDays: 21,
    origin: "Producteurs d'œufs du Canada",
    badges: ["Calibre A", "Protéines complètes", "Fermes canadiennes"],
    nutrition: { serving: "1 œuf (53g)", calories: 70, protein: "6g", carbs: "0g", fat: "5g", choline: "140mg" },
    storageTipFr: "Conserver dans leur carton d'origine sur une tablette du réfrigérateur.",
    storageTipEn: "Store in original carton on a fridge shelf to maintain moisture balance.",
  },
  {
    code: "CNF_DAIRY_06",
    upc: "056800123456",
    nameFr: "Yogourt grec nature 0% riche en protéines",
    nameEn: "Plain 0% High-Protein Greek Yogurt",
    brand: "Oikos / Iögo / Liberté / Kirkland",
    category: "Dairy & Eggs",
    categoryFr: "Produits laitiers & œufs",
    location: "Fridge",
    unopenedShelfLifeDays: 28,
    openedShelfLifeDays: 10,
    origin: "Canada",
    badges: ["17g de protéines", "Sans sucre ajouté", "Lait canadien"],
    nutrition: { serving: "175g (3/4 tasse)", calories: 100, protein: "17g", carbs: "6g", fat: "0g", calcium: "200mg" },
    storageTipFr: "Garder bien fermé au réfrigérateur. Ne pas jeter le petit-lait riche en protéines.",
    storageTipEn: "Stir whey liquid back in for maximum calcium and protein.",
  },

  // --- MEATS & POULTRY (Canadian Cuts & Standards) ---
  {
    code: "CNF_MEAT_01",
    upc: "060383182903",
    nameFr: "Poitrines de poulet frais désossées sans peau",
    nameEn: "Fresh Boneless Skinless Chicken Breasts",
    brand: "Exceldor / Flamingo / Olymel / Le Choix du Président",
    category: "Meat & Seafood",
    categoryFr: "Viandes & Poissons",
    location: "Fridge",
    unopenedShelfLifeDays: 3,
    openedShelfLifeDays: 2,
    monthsFrozenShelfLife: 9,
    origin: "Poulet élevé par un producteur canadien",
    badges: ["Poulet canadien", "Sans hormones ajoutées", "Élevé au Canada"],
    nutrition: { serving: "100g cuit", calories: 165, protein: "31g", carbs: "0g", fat: "3.6g", iron: "1mg" },
    storageTipFr: "Cuire dans les 2 à 3 jours ou congeler immédiatement dans un sac sous vide ou sac congélation.",
    storageTipEn: "Cook within 2-3 days or freeze immediately in freezer zip bag.",
  },
  {
    code: "CNF_MEAT_02",
    upc: "060383002341",
    nameFr: "Bœuf haché maigre canadien 100%",
    nameEn: "Canadian 100% Lean Ground Beef",
    brand: "Bœuf Canadien Certifié / Sterling Silver",
    category: "Meat & Seafood",
    categoryFr: "Viandes & Poissons",
    location: "Fridge",
    unopenedShelfLifeDays: 3,
    openedShelfLifeDays: 2,
    monthsFrozenShelfLife: 4,
    origin: "Bœuf du Canada (Alberta / Ontario / Québec)",
    badges: ["Bœuf canadien", "Catégorie AA / AAA", "Sans additifs"],
    nutrition: { serving: "100g cuit", calories: 215, protein: "26g", carbs: "0g", fat: "11g", iron: "2.8mg" },
    storageTipFr: "Conserver sur la tablette du bas au frigo. Décongeler lentement au réfrigérateur.",
    storageTipEn: "Store on lowest shelf of fridge. Thaw safely inside fridge overnight.",
  },
  {
    code: "CNF_MEAT_03",
    upc: "060383567890",
    nameFr: "Filet de saumon de l'Atlantique canadien frais",
    nameEn: "Fresh Canadian Atlantic Salmon Fillet",
    brand: "Pêcheries Atlantiques / Jail Island",
    category: "Meat & Seafood",
    categoryFr: "Viandes & Poissons",
    location: "Fridge",
    unopenedShelfLifeDays: 2,
    openedShelfLifeDays: 1,
    monthsFrozenShelfLife: 3,
    origin: "Nouveau-Brunswick / Nouvelle-Écosse, Canada",
    badges: ["Oméga-3", "Pêche / Aquaculture responsable", "Produit du Canada"],
    nutrition: { serving: "100g", calories: 208, protein: "20g", carbs: "0g", fat: "13g", omega3: "2.3g" },
    storageTipFr: "Idéalement consommer le jour même ou le lendemain. Placer sur un lit de glace au frigo.",
    storageTipEn: "Cook within 24-48 hours. Freeze tightly wrapped for longer storage.",
  },
  {
    code: "CNF_MEAT_04",
    upc: "068700023411",
    nameFr: "Bacon fumé au bois de pommier naturel",
    nameEn: "Applewood Smoked Canadian Bacon",
    brand: "Maple Leaf / Olymel / Lafleur",
    category: "Meat & Seafood",
    categoryFr: "Viandes & Poissons",
    location: "Fridge",
    unopenedShelfLifeDays: 45,
    openedShelfLifeDays: 7,
    monthsFrozenShelfLife: 3,
    origin: "Porc du Québec / Canada",
    badges: ["Porc canadien", "Fumé naturellement", "Aliments du Québec"],
    nutrition: { serving: "2 tranches (30g)", calories: 90, protein: "6g", carbs: "0g", fat: "7g", sodium: "320mg" },
    storageTipFr: "Après ouverture, envelopper fermement dans une pellicule plastique ou papier alu.",
    storageTipEn: "Keep tightly sealed after opening; freeze extra portions.",
  },

  // --- BAKERY & GRAINS (Canadian Mills & Breads) ---
  {
    code: "CNF_BAKERY_01",
    upc: "061077123450",
    nameFr: "Pain 100% blé entier tranché St-Méthode",
    nameEn: "St-Méthode 100% Whole Wheat Sliced Bread",
    brand: "Boulangerie St-Méthode / Bon Matin / D'Italiano",
    category: "Bakery",
    categoryFr: "Boulangerie",
    location: "Pantry",
    unopenedShelfLifeDays: 8,
    openedShelfLifeDays: 5,
    monthsFrozenShelfLife: 3,
    origin: "Farine de blé du Québec et de l'Ouest canadien",
    badges: ["Aliments du Québec", "Grains entiers", "Source élevée de fibres"],
    nutrition: { serving: "2 tranches (75g)", calories: 170, protein: "8g", carbs: "32g", fat: "1.5g", fiber: "5g" },
    storageTipFr: "Conserver dans un endroit frais et sec. Se congèle parfaitement en tranches.",
    storageTipEn: "Store in bread box or pantry. Freeze whole loaf and toast directly from frozen.",
  },
  {
    code: "CNF_BAKERY_02",
    upc: "059749876543",
    nameFr: "Bagels style Montréal aux graines de sésame",
    nameEn: "Montreal-Style Sesame Seed Bagels",
    brand: "Première Moisson / Fairmount / St-Viateur",
    category: "Bakery",
    categoryFr: "Boulangerie",
    location: "Pantry",
    unopenedShelfLifeDays: 4,
    openedShelfLifeDays: 2,
    monthsFrozenShelfLife: 4,
    origin: "Montréal, Québec, Canada",
    badges: ["Tradition montréalaise", "Cuit au four à bois", "Aliments du Québec"],
    nutrition: { serving: "1 bagel (90g)", calories: 270, protein: "9g", carbs: "51g", fat: "3.5g", iron: "3.5mg" },
    storageTipFr: "Trancher en deux avant de congeler pour griller directement sans décongélation.",
    storageTipEn: "Slice before freezing so you can pop straight into the toaster.",
  },
  {
    code: "CNF_BAKERY_03",
    upc: "058703123456",
    nameFr: "Farine tout usage enrichie non blanchie Five Roses",
    nameEn: "Five Roses Enriched Unbleached All-Purpose Flour",
    brand: "Five Roses / Robin Hood",
    category: "Pantry Staples",
    categoryFr: "Garde-manger",
    location: "Pantry",
    unopenedShelfLifeDays: 365,
    openedShelfLifeDays: 180,
    origin: "Blé dur canadien de l'Ouest (CWRS)",
    badges: ["100% blé canadien", "Non blanchie", "Qualité meunerie"],
    nutrition: { serving: "30g (1/4 tasse)", calories: 110, protein: "4g", carbs: "22g", fat: "0.3g", iron: "1.4mg" },
    storageTipFr: "Transférer dans un contenant hermétique dans un endroit frais et sombre.",
    storageTipEn: "Store in an airtight container in a cool, dry, dark pantry.",
  },

  // --- CANADIAN PANTRY & MAPLE SPECIALTIES ---
  {
    code: "CNF_PANTRY_01",
    upc: "062000123456",
    nameFr: "Sirop d'érable pur 100% du Québec (Ambré goût riche)",
    nameEn: "100% Pure Quebec Maple Syrup (Amber Rich Taste)",
    brand: "Érablière du Québec / Sélection / Irresistibles",
    category: "Pantry Staples",
    categoryFr: "Garde-manger",
    location: "Fridge",
    unopenedShelfLifeDays: 730,
    openedShelfLifeDays: 365,
    origin: "Québec, Canada (Producteurs et productrices acéricoles du Québec)",
    badges: ["Aliments du Québec", "100% pur", "Goût riche"],
    nutrition: { serving: "60 mL (1/4 tasse)", calories: 216, protein: "0g", carbs: "53g", fat: "0g", potassium: "204mg" },
    storageTipFr: "Après ouverture de la conserve ou bouteille, conserver TOUJOURS au réfrigérateur pour éviter les moisissures.",
    storageTipEn: "After opening, ALWAYS refrigerate to prevent crystallization and mold.",
  },
  {
    code: "CNF_PANTRY_02",
    upc: "064500001234",
    nameFr: "Fèves au lard à l'ancienne à la mélasse Clark",
    nameEn: "Clark Traditional Baked Beans in Molasses",
    brand: "Clark / Heinz Canada",
    category: "Canned Goods",
    categoryFr: "Conserves & Légumineuses",
    location: "Pantry",
    unopenedShelfLifeDays: 730,
    openedShelfLifeDays: 4,
    origin: "Canada",
    badges: ["Riche en fibres", "Sans gluten naturel", "Classique québécois"],
    nutrition: { serving: "250 mL (1 tasse)", calories: 240, protein: "12g", carbs: "48g", fat: "1.5g", fiber: "10g" },
    storageTipFr: "Après ouverture de la boîte, transvider dans un plat hermétique et réfrigérer jusqu'à 4 jours.",
    storageTipEn: "Transfer leftovers from metal can into glass container; refrigerate.",
  },
  {
    code: "CNF_PANTRY_03",
    upc: "060500123456",
    nameFr: "Soupe aux pois à l'ancienne avec jambon Habitant",
    nameEn: "Habitant French-Canadian Pea Soup with Ham",
    brand: "Habitant / Campbell's Canada",
    category: "Canned Goods",
    categoryFr: "Conserves & Légumineuses",
    location: "Pantry",
    unopenedShelfLifeDays: 730,
    openedShelfLifeDays: 4,
    origin: "Canada",
    badges: ["Recette traditionnelle québécoise", "Pois jaunes entiers"],
    nutrition: { serving: "250 mL", calories: 170, protein: "9g", carbs: "27g", fat: "2.5g", fiber: "6g" },
    storageTipFr: "Garde-manger. Transférer dans un bol scellé après ouverture au réfrigérateur.",
    storageTipEn: "Keep in pantry. Store opened soup in fridge up to 4 days.",
  },
  {
    code: "CNF_PANTRY_04",
    upc: "068700987654",
    nameFr: "Sauce BBQ St-Hubert originale en boîte",
    nameEn: "St-Hubert Original BBQ Gravy Sauce",
    brand: "St-Hubert",
    category: "Condiments",
    categoryFr: "Sauces & Condiments",
    location: "Pantry",
    unopenedShelfLifeDays: 730,
    openedShelfLifeDays: 5,
    origin: "Québec, Canada",
    badges: ["Aliments du Québec", "Recette originale 1951"],
    nutrition: { serving: "60 mL", calories: 30, protein: "0.5g", carbs: "6g", fat: "0.5g", sodium: "410mg" },
    storageTipFr: "Classique des rôtisseries québécoises. Réfrigérer après ouverture.",
    storageTipEn: "Iconic Quebec rotisserie sauce. Refrigerate leftovers.",
  },
  {
    code: "CNF_PANTRY_05",
    upc: "067300123456",
    nameFr: "Jus de pomme pur 100% Oasis / Rougemont",
    nameEn: "Oasis / Rougemont 100% Pure Apple Juice",
    brand: "Oasis / Rougemont / Lassonde",
    category: "Beverages",
    categoryFr: "Boissons",
    location: "Pantry",
    unopenedShelfLifeDays: 270,
    openedShelfLifeDays: 10,
    origin: "Rougemont, Québec, Canada",
    badges: ["Aliments du Québec", "Sans sucre ajouté", "Vitamine C ajoutée"],
    nutrition: { serving: "250 mL", calories: 110, protein: "0g", carbs: "28g", fat: "0g", vitaminC: "100%" },
    storageTipFr: "Garder au garde-manger. Mettre au frigo avant de servir; consommer dans les 10 jours après ouverture.",
    storageTipEn: "Pantry stable unopened. Refrigerate after opening and drink within 10 days.",
  },
];

// ============================================================================
// 3. SEARCH & RESOLUTION ENGINE
// ============================================================================

/**
 * Searches the Canadian Nutrient File and PLU database for keyword matches
 */
export function searchCanadianAndPluDatabase(query, language = "FR") {
  if (!query || typeof query !== "string") return [];
  const normalized = query.toLowerCase().trim();
  const isFr = (language || "FR").toUpperCase().startsWith("FR");

  const results = [];
  const seenCodes = new Set();

  // 1. Check PLU produce database
  // If query is a 4- or 5-digit number
  const isNumeric = /^\d{4,5}$/.test(normalized);
  if (isNumeric) {
    const pluKey = normalized.length === 5 && normalized.startsWith("9") ? normalized.slice(1) : normalized;
    const isOrganic = normalized.length === 5 && normalized.startsWith("9");

    if (IFPS_PLU_CODES[pluKey]) {
      const p = IFPS_PLU_CODES[pluKey];
      results.push({
        source: "IFPS_PLU",
        sourceLabel: isFr ? "🏷️ Base PLU Internationale (Fruits & Légumes)" : "🏷️ IFPS Global PLU Produce Database",
        code: normalized,
        name: isOrganic
          ? (isFr ? `${p.nameFr} (Biologique)` : `${p.nameEn} (Organic)`)
          : (isFr ? p.nameFr : p.nameEn),
        nameFr: isOrganic ? `${p.nameFr} (Biologique)` : p.nameFr,
        nameEn: isOrganic ? `${p.nameEn} (Organic)` : p.nameEn,
        category: isFr ? p.categoryFr : p.category,
        categoryEn: p.category,
        brand: isOrganic ? "Certifié Biologique" : "Produit frais",
        gradeOrigin: `Code PLU #${normalized} • ${p.origin}`,
        location: p.location,
        shelfLifeDays: p.shelfLifeDays,
        storageTip: isFr ? p.storageTipFr : p.storageTipEn,
        nutrition: { calories: p.calories, protein: p.protein, carbs: p.carbs, fat: p.fat, fiber: p.fiber },
      });
      seenCodes.add(normalized);
    }
  }

  // 2. Keyword search on IFPS PLU produce
  for (const [code, p] of Object.entries(IFPS_PLU_CODES)) {
    if (seenCodes.has(code)) continue;
    const matchFr = p.nameFr.toLowerCase().includes(normalized) || p.variety.toLowerCase().includes(normalized);
    const matchEn = p.nameEn.toLowerCase().includes(normalized) || p.variety.toLowerCase().includes(normalized);

    if (matchFr || matchEn) {
      seenCodes.add(code);
      results.push({
        source: "IFPS_PLU",
        sourceLabel: isFr ? "🏷️ Base PLU Fruits & Légumes" : "🏷️ IFPS Produce Database",
        code: code,
        name: isFr ? p.nameFr : p.nameEn,
        nameFr: p.nameFr,
        nameEn: p.nameEn,
        category: isFr ? p.categoryFr : p.category,
        categoryEn: p.category,
        brand: "Produit frais",
        gradeOrigin: `Pastille PLU #${code} • ${p.origin}`,
        location: p.location,
        shelfLifeDays: p.shelfLifeDays,
        storageTip: isFr ? p.storageTipFr : p.storageTipEn,
        nutrition: { calories: p.calories, protein: p.protein, carbs: p.carbs, fat: p.fat, fiber: p.fiber },
      });
    }
  }

  // 3. Search Canadian Nutrient File (CNF)
  for (const cnf of CANADIAN_NUTRIENT_FILE_CATALOG) {
    if (seenCodes.has(cnf.code)) continue;
    const matchName = cnf.nameFr.toLowerCase().includes(normalized) || cnf.nameEn.toLowerCase().includes(normalized);
    const matchBrand = cnf.brand.toLowerCase().includes(normalized);
    const matchUpc = cnf.upc === normalized;

    if (matchName || matchBrand || matchUpc) {
      seenCodes.add(cnf.code);
      results.push({
        source: "CANADIAN_NUTRIENT_FILE",
        sourceLabel: isFr ? "🍁 Fichier canadien sur les éléments nutritifs (Santé Canada)" : "🍁 Canadian Nutrient File (Health Canada)",
        code: cnf.code,
        upc: cnf.upc,
        name: isFr ? cnf.nameFr : cnf.nameEn,
        nameFr: cnf.nameFr,
        nameEn: cnf.nameEn,
        category: isFr ? cnf.categoryFr : cnf.category,
        categoryEn: cnf.category,
        brand: cnf.brand,
        gradeOrigin: cnf.origin,
        location: cnf.location,
        shelfLifeDays: cnf.unopenedShelfLifeDays,
        storageTip: isFr ? cnf.storageTipFr : cnf.storageTipEn,
        dietaryBadges: cnf.badges,
        nutrition: cnf.nutrition,
      });
    }
  }

  return results;
}

/**
 * High-precision UPC/EAN Barcode Resolver
 * Checks Canadian database and Open Food Facts (Canada node first, then Global)
 */
export async function resolveBarcodeUnified(barcode, language = "FR") {
  const cleanCode = String(barcode || "").trim().replace(/[^0-9]/g, "");
  const isFr = (language || "FR").toUpperCase().startsWith("FR");

  if (!cleanCode || cleanCode.length < 4) {
    throw new Error("Invalid barcode or PLU code");
  }

  // Check 1: IFPS PLU produce code (4-5 digits)
  if (cleanCode.length === 4 || cleanCode.length === 5) {
    const isOrganic = cleanCode.length === 5 && cleanCode.startsWith("9");
    const pluKey = isOrganic ? cleanCode.slice(1) : cleanCode;

    if (IFPS_PLU_CODES[pluKey]) {
      const p = IFPS_PLU_CODES[pluKey];
      const title = isOrganic
        ? (isFr ? `${p.nameFr} (Biologique)` : `${p.nameEn} (Organic)`)
        : (isFr ? p.nameFr : p.nameEn);

      return {
        success: true,
        source: "IFPS_PLU",
        sourceLabel: isFr ? "🏷️ Base PLU Internationale (Aliments frais)" : "🏷️ IFPS Global PLU Produce Standard",
        barcode: cleanCode,
        item: {
          name: title,
          nameFr: isOrganic ? `${p.nameFr} (Biologique)` : p.nameFr,
          nameEn: isOrganic ? `${p.nameEn} (Organic)` : p.nameEn,
          brand: isOrganic ? "Certifié Biologique" : "Produit frais",
          category: isFr ? p.categoryFr : p.category,
          categoryEn: p.category,
          quantity: 1,
          unit: "pcs",
          recommendedLocation: p.location,
          estimatedShelfLifeDays: p.shelfLifeDays,
          monthsFrozenShelfLife: 10,
          gradeOrigin: `Pastille PLU #${cleanCode} • ${p.origin}`,
          packagingFormat: isFr ? "Fruit/légume frais en vrac" : "Whole fresh loose produce",
          dietaryBadges: isOrganic ? ["Biologique", "Produits frais", "Sans emballage"] : ["Produits frais", "Sans emballage"],
          storageTip: isFr ? p.storageTipFr : p.storageTipEn,
          storageReason: isFr ? "Conserver selon les recommandations de fraîcheur maraîchère." : "Store according to fresh produce best practices.",
          freezerTip: isFr ? "Laver, peler ou découper avant de congeler pour smoothies ou cuisine." : "Chop or peel before freezing for smoothies or recipes.",
          nutrition: p.calories ? { calories: p.calories, protein: p.protein, carbs: p.carbs, fat: p.fat, fiber: p.fiber } : null,
          barcode: cleanCode,
        },
      };
    }
  }

  // Check 2: Canadian Nutrient File / Canadian retail catalog match
  const cnfMatch = CANADIAN_NUTRIENT_FILE_CATALOG.find((c) => c.upc === cleanCode);
  if (cnfMatch) {
    return {
      success: true,
      source: "CANADIAN_NUTRIENT_FILE",
      sourceLabel: isFr ? "🍁 Fichier canadien sur les éléments nutritifs (Santé Canada)" : "🍁 Canadian Nutrient File (Health Canada)",
      barcode: cleanCode,
      item: {
        name: isFr ? cnfMatch.nameFr : cnfMatch.nameEn,
        nameFr: cnfMatch.nameFr,
        nameEn: cnfMatch.nameEn,
        brand: cnfMatch.brand,
        category: isFr ? cnfMatch.categoryFr : cnfMatch.category,
        categoryEn: cnfMatch.category,
        quantity: 1,
        unit: "pcs",
        recommendedLocation: cnfMatch.location,
        unopenedShelfLifeDays: cnfMatch.unopenedShelfLifeDays,
        openedShelfLifeDays: cnfMatch.openedShelfLifeDays,
        estimatedShelfLifeDays: cnfMatch.unopenedShelfLifeDays,
        monthsFrozenShelfLife: cnfMatch.monthsFrozenShelfLife || 6,
        gradeOrigin: cnfMatch.origin,
        dietaryBadges: cnfMatch.badges,
        storageTip: isFr ? cnfMatch.storageTipFr : cnfMatch.storageTipEn,
        nutrition: cnfMatch.nutrition,
        barcode: cleanCode,
      },
    };
  }

  // Check 3: Query Canadian Open Food Facts first (ca.openfoodfacts.org), then global
  const endpoints = [
    `https://ca.openfoodfacts.org/api/v2/product/${cleanCode}.json`,
    `https://world.openfoodfacts.org/api/v2/product/${cleanCode}.json`,
  ];

  for (const url of endpoints) {
    try {
      const response = await fetch(url, {
        headers: {
          "User-Agent": "PantryoCanadaFoodTracker/2.0 (Canadian Grocery Engine; contact@pantryo.app)",
        },
        timeout: 5000,
      });

      if (response.ok) {
        const data = await response.json();
        if (data && data.status === 1 && data.product) {
          const prod = data.product;
          const brand = prod.brands ? prod.brands.split(",")[0].trim() : null;
          let nameFr = prod.product_name_fr || prod.generic_name_fr || null;
          let nameEn = prod.product_name_en || prod.generic_name_en || prod.product_name || "Food Product";

          if (brand) {
            if (nameFr && !nameFr.toLowerCase().includes(brand.toLowerCase())) {
              nameFr = `${brand} ${nameFr}`;
            }
            if (nameEn && !nameEn.toLowerCase().includes(brand.toLowerCase())) {
              nameEn = `${brand} ${nameEn}`;
            }
          }

          if (!nameFr && nameEn) {
            nameFr = translateFoodItem(nameEn, "FR");
          }
          if (!nameEn && nameFr) {
            nameEn = translateFoodItem(nameFr, "EN");
          }
          if (!nameFr) nameFr = "Produit alimentaire";
          if (!nameEn) nameEn = "Food Product";

          let name = isFr ? (nameFr || nameEn) : (nameEn || nameFr);

          // Detect category
          let category = "Pantry Staples";
          let categoryFr = "Garde-manger";
          const catTags = (prod.categories_tags || []).join(" ").toLowerCase();

          if (catTags.includes("dairy") || catTags.includes("cheese") || catTags.includes("milk") || catTags.includes("yogurt") || catTags.includes("egg")) {
            category = "Dairy & Eggs";
            categoryFr = "Produits laitiers & œufs";
          } else if (catTags.includes("meat") || catTags.includes("fish") || catTags.includes("seafood") || catTags.includes("poultry") || catTags.includes("beef") || catTags.includes("chicken")) {
            category = "Meat & Seafood";
            categoryFr = "Viandes & Poissons";
          } else if (catTags.includes("fruit") || catTags.includes("vegetable") || catTags.includes("produce") || catTags.includes("salad")) {
            category = "Produce";
            categoryFr = "Produits frais";
          } else if (catTags.includes("beverage") || catTags.includes("drink") || catTags.includes("juice") || catTags.includes("water") || catTags.includes("coffee") || catTags.includes("tea")) {
            category = "Beverages";
            categoryFr = "Boissons";
          } else if (catTags.includes("bread") || catTags.includes("bakery") || catTags.includes("pastry") || catTags.includes("cake")) {
            category = "Bakery";
            categoryFr = "Boulangerie";
          } else if (catTags.includes("frozen")) {
            category = "Frozen Meals";
            categoryFr = "Surgelés";
          }

          // Recommended location
          let recommendedLocation = "Pantry";
          if (["Dairy & Eggs", "Meat & Seafood", "Produce"].includes(category)) {
            recommendedLocation = "Fridge";
          } else if (category === "Frozen Meals") {
            recommendedLocation = "Freezer";
          }

          // Badges from Nutri-Score / Eco-Score
          const badges = [];
          if (prod.nutriscore_grade) badges.push(`Nutri-Score ${prod.nutriscore_grade.toUpperCase()}`);
          if (prod.ecoscore_grade) badges.push(`Eco-Score ${prod.ecoscore_grade.toUpperCase()}`);
          if (prod.nova_group) badges.push(`NOVA Groupe ${prod.nova_group}`);
          if (prod.countries_tags && prod.countries_tags.some((c) => c.includes("canada"))) {
            badges.push("Marché canadien");
          }

          const nutrition = prod.nutriments ? {
            serving: prod.serving_size || "100g",
            calories: prod.nutriments["energy-kcal_100g"] || prod.nutriments["energy-kcal"] || null,
            protein: prod.nutriments.proteins_100g ? `${prod.nutriments.proteins_100g}g` : null,
            carbs: prod.nutriments.carbohydrates_100g ? `${prod.nutriments.carbohydrates_100g}g` : null,
            fat: prod.nutriments.fat_100g ? `${prod.nutriments.fat_100g}g` : null,
            sodium: prod.nutriments.sodium_100g ? `${Math.round(prod.nutriments.sodium_100g * 1000)}mg` : null,
          } : null;

          return {
            success: true,
            source: url.includes("ca.openfoodfacts.org") ? "OPEN_FOOD_FACTS_CA" : "OPEN_FOOD_FACTS_GLOBAL",
            sourceLabel: url.includes("ca.openfoodfacts.org")
              ? (isFr ? "🇨🇦 Open Food Facts (Canada)" : "🇨🇦 Open Food Facts (Canada)")
              : (isFr ? "🌍 Open Food Facts (Mondial)" : "🌍 Open Food Facts (Global)"),
            barcode: cleanCode,
            item: {
              name: name.trim(),
              nameFr: nameFr ? nameFr.trim() : name.trim(),
              nameEn: nameEn ? nameEn.trim() : name.trim(),
              brand,
              category: isFr ? categoryFr : category,
              categoryEn: category,
              quantity: 1,
              unit: prod.quantity || "1 unité",
              recommendedLocation,
              estimatedShelfLifeDays: recommendedLocation === "Fridge" ? 14 : recommendedLocation === "Freezer" ? 180 : 60,
              monthsFrozenShelfLife: 6,
              gradeOrigin: prod.origins || (prod.countries_tags ? prod.countries_tags.join(", ").replace(/en:/g, "") : null),
              packagingFormat: prod.packaging || (isFr ? "Emballage commercial" : "Retail package"),
              dietaryBadges: badges,
              storageTip: isFr ? `Conserver au ${recommendedLocation.toLowerCase()} pour une fraîcheur optimale.` : `Store in ${recommendedLocation.toLowerCase()} for maximum freshness.`,
              nutrition,
              imageUrl: prod.image_front_url || prod.image_url || null,
              barcode: cleanCode,
            },
          };
        }
      }
    } catch (e) {
      // Continue to next endpoint
      console.warn(`[GroceryDb] Error querying ${url}:`, e.message);
    }
  }

  // Check 4: Return generic clean item with barcode
  return {
    success: true,
    source: "UNKNOWN_BARCODE",
    sourceLabel: isFr ? "Code-barres non répertorié" : "Unindexed Barcode",
    barcode: cleanCode,
    item: {
      name: isFr ? `Article UPC #${cleanCode.slice(-4)}` : `UPC Item #${cleanCode.slice(-4)}`,
      nameFr: `Article UPC #${cleanCode.slice(-4)}`,
      nameEn: `UPC Item #${cleanCode.slice(-4)}`,
      brand: null,
      category: isFr ? "Garde-manger" : "Pantry Staples",
      categoryEn: "Pantry Staples",
      quantity: 1,
      unit: "pcs",
      recommendedLocation: "Pantry",
      estimatedShelfLifeDays: 30,
      monthsFrozenShelfLife: 6,
      barcode: cleanCode,
    },
  };
}
